import {
  CorporateThemeAccordin,
  CorporateThemeActions,
  CorporateThemeAlert,
  CorporateThemeBadge,
  CorporateThemeButton,
  CorporateThemeCalendar,
  CorporateThemeCard,
  CorporateThemeChat,
  CorporateThemeCheckbox,
  CorporateThemeContextMenu,
  CorporateThemeCore,
  CorporateThemeDateTimePicker,
  CorporateThemeFormField,
  CorporateThemeIcon,
  CorporateThemeInput,
  CorporateThemeLayout,
  CorporateThemeListItem,
  CorporateThemeMenu,
  CorporateThemeOption,
  CorporateThemePopover,
  CorporateThemeProgressBar,
  CorporateThemeRadio,
  CorporateThemeSearch,
  CorporateThemeSelect,
  CorporateThemeSidebar,
  CorporateThemeLoader,
  CorporateThemeStepper,
  CorporateThemeTabset,
  CorporateThemeTag,
  CorporateThemeToastr,
  CorporateThemeToggle,
  CorporateThemeTooltip,
  CorporateThemeUser,
  CorporateThemeVariables
} from './corporate-theme';
import { attachFunctions } from './functions/attach-functions';
import { NebularThemeBase } from './types';

const _CORPORATE_THEME: NebularThemeBase = {
  ...CorporateThemeCore,
  ...CorporateThemeAccordin,
  ...CorporateThemeActions,
  ...CorporateThemeAlert,
  ...CorporateThemeBadge,
  ...CorporateThemeButton,
  ...CorporateThemeCalendar,
  ...CorporateThemeCard,
  ...CorporateThemeChat,
  ...CorporateThemeCheckbox,
  ...CorporateThemeContextMenu,
  ...CorporateThemeDateTimePicker,
  ...CorporateThemeFormField,
  ...CorporateThemeIcon,
  ...CorporateThemeInput,
  ...CorporateThemeLayout,
  ...CorporateThemeListItem,
  ...CorporateThemeMenu,
  ...CorporateThemeOption,
  ...CorporateThemePopover,
  ...CorporateThemeProgressBar,
  ...CorporateThemeRadio,
  ...CorporateThemeSearch,
  ...CorporateThemeSelect,
  ...CorporateThemeSidebar,
  ...CorporateThemeLoader,
  ...CorporateThemeStepper,
  ...CorporateThemeTabset,
  ...CorporateThemeTag,
  ...CorporateThemeToastr,
  ...CorporateThemeToggle,
  ...CorporateThemeTooltip,
  ...CorporateThemeUser,
  ...CorporateThemeVariables
};

export const CORPORATE_THEME = attachFunctions(_CORPORATE_THEME);
