import {
  DarkThemeAccordin,
  DarkThemeActions,
  DarkThemeAlert,
  DarkThemeBadge,
  DarkThemeButton,
  DarkThemeCalendar,
  DarkThemeCard,
  DarkThemeChat,
  DarkThemeCheckbox,
  DarkThemeContextMenu,
  DarkThemeCore,
  DarkThemeDateTimePicker,
  DarkThemeFormField,
  DarkThemeIcon,
  DarkThemeInput,
  DarkThemeLayout,
  DarkThemeListItem,
  DarkThemeMenu,
  DarkThemeOption,
  DarkThemePopover,
  DarkThemeProgressBar,
  DarkThemeRadio,
  DarkThemeSearch,
  DarkThemeSelect,
  DarkThemeSidebar,
  DarkThemeLoader,
  DarkThemeStepper,
  DarkThemeTabset,
  DarkThemeTag,
  DarkThemeToastr,
  DarkThemeToggle,
  DarkThemeTooltip,
  DarkThemeUser,
  DarkThemeVariables
} from './dark-theme';
import { attachFunctions } from './functions/attach-functions';
import { NebularThemeBase } from './types';

const _DARK_THEME: NebularThemeBase = {
  ...DarkThemeCore,
  ...DarkThemeAccordin,
  ...DarkThemeActions,
  ...DarkThemeAlert,
  ...DarkThemeBadge,
  ...DarkThemeButton,
  ...DarkThemeCalendar,
  ...DarkThemeCard,
  ...DarkThemeChat,
  ...DarkThemeCheckbox,
  ...DarkThemeContextMenu,
  ...DarkThemeDateTimePicker,
  ...DarkThemeFormField,
  ...DarkThemeIcon,
  ...DarkThemeInput,
  ...DarkThemeLayout,
  ...DarkThemeListItem,
  ...DarkThemeMenu,
  ...DarkThemeOption,
  ...DarkThemePopover,
  ...DarkThemeProgressBar,
  ...DarkThemeRadio,
  ...DarkThemeSearch,
  ...DarkThemeSelect,
  ...DarkThemeSidebar,
  ...DarkThemeLoader,
  ...DarkThemeStepper,
  ...DarkThemeTabset,
  ...DarkThemeTag,
  ...DarkThemeToastr,
  ...DarkThemeToggle,
  ...DarkThemeTooltip,
  ...DarkThemeUser,
  ...DarkThemeVariables
};

export const DARK_THEME = attachFunctions(_DARK_THEME);
