import {
  DefaultThemeAccordin,
  DefaultThemeActions,
  DefaultThemeAlert,
  DefaultThemeBadge,
  DefaultThemeButton,
  DefaultThemeCalendar,
  DefaultThemeCard,
  DefaultThemeChat,
  DefaultThemeCheckbox,
  DefaultThemeContextMenu,
  DefaultThemeCore,
  DefaultThemeDateTimePicker,
  DefaultThemeFormField,
  DefaultThemeIcon,
  DefaultThemeInput,
  DefaultThemeLayout,
  DefaultThemeListItem,
  DefaultThemeMenu,
  DefaultThemeOption,
  DefaultThemePopover,
  DefaultThemeProgressBar,
  DefaultThemeRadio,
  DefaultThemeSearch,
  DefaultThemeSelect,
  DefaultThemeSidebar,
  DefaultThemeLoader,
  DefaultThemeStepper,
  DefaultThemeTabset,
  DefaultThemeTag,
  DefaultThemeToastr,
  DefaultThemeToggle,
  DefaultThemeTooltip,
  DefaultThemeUser,
  DefaultThemeVariables
} from './default-theme';
import { attachFunctions } from './functions/attach-functions';
import { NebularThemeBase } from './types';

const _DEFAULT_THEME: NebularThemeBase = {
  ...DefaultThemeCore,
  ...DefaultThemeAccordin,
  ...DefaultThemeActions,
  ...DefaultThemeAlert,
  ...DefaultThemeBadge,
  ...DefaultThemeButton,
  ...DefaultThemeCalendar,
  ...DefaultThemeCard,
  ...DefaultThemeChat,
  ...DefaultThemeCheckbox,
  ...DefaultThemeContextMenu,
  ...DefaultThemeDateTimePicker,
  ...DefaultThemeFormField,
  ...DefaultThemeIcon,
  ...DefaultThemeInput,
  ...DefaultThemeLayout,
  ...DefaultThemeListItem,
  ...DefaultThemeMenu,
  ...DefaultThemeOption,
  ...DefaultThemePopover,
  ...DefaultThemeProgressBar,
  ...DefaultThemeRadio,
  ...DefaultThemeSearch,
  ...DefaultThemeSelect,
  ...DefaultThemeSidebar,
  ...DefaultThemeLoader,
  ...DefaultThemeStepper,
  ...DefaultThemeTabset,
  ...DefaultThemeTag,
  ...DefaultThemeToastr,
  ...DefaultThemeToggle,
  ...DefaultThemeTooltip,
  ...DefaultThemeUser,
  ...DefaultThemeVariables
};

export const DEFAULT_THEME = attachFunctions(_DEFAULT_THEME);
