export interface NebularThemeDateTimePicker {
  datepicker_background_color: any;
  datepicker_border_color: any;
  datepicker_border_style: any;
  datepicker_border_width: any;
  datepicker_border_radius: any;
  datepicker_shadow: any;

  timepicker_cell_text_color: any;
  timepicker_cell_hover_background_color: any;
  timepicker_cell_hover_text_color: any;
  timepicker_cell_focus_background_color: any;
  timepicker_cell_focus_text_color: any;
  timepicker_cell_active_background_color: any;
  timepicker_cell_active_text_color: any;
  timepicker_cell_text_font_size: any;
  timepicker_cell_text_font_family: any;
  timepicker_cell_text_line_height: any;
  timepicker_cell_text_font_weight: any;
  timepicker_cell_height: any;
  timepicker_header_cell_text_color: any;
  timepicker_header_cell_text_font_size: any;
  timepicker_header_cell_text_font_family: any;
  timepicker_header_cell_height: any;
  timepicker_header_cell_text_line_height: any;
  timepicker_header_cell_text_font_weight: any;
  timepicker_border_color: any;
  timepicker_border_style: any;
  timepicker_border_width: any;
  timepicker_scrollbar_color: any;
  timepicker_scrollbar_background_color: any;
  timepicker_scrollbar_width: any;
  timepicker_single_column_width: any;
  timepicker_multiple_column_width: any;
  timepicker_title_height: any;
  timepicker_title_padding: any;
  timepicker_container_width: any;
  timepicker_container_height: any;
}
