import { NebularThemeToastr } from '../types/nebular-theme';

export const DefaultThemeToastr: NebularThemeToastr = {
  toastr_border_style: 'solid',
  toastr_border_width: '1px',
  toastr_border_radius: 'var(--border-radius)',
  toastr_padding: '1rem',
  toastr_shadow: 'var(--shadow)',

  toastr_text_font_family: 'var(--text-paragraph-2-font-family)',
  toastr_text_font_size: 'var(--text-paragraph-2-font-size)',
  toastr_text_font_weight: 'var(--text-paragraph-2-font-weight)',
  toastr_text_line_height: 'var(--text-paragraph-2-line-height)',
  toastr_title_text_font_family: 'var(--text-subtitle-font-family)',
  toastr_title_text_font_size: 'var(--text-subtitle-font-size)',
  toastr_title_text_font_weight: 'var(--text-subtitle-font-weight)',
  toastr_title_text_line_height: 'var(--text-subtitle-line-height)',

  toastr_basic_background_color: 'var(--background-basic-color-1)',
  toastr_basic_border_color: 'var(--border-basic-color-3)',
  toastr_basic_text_color: 'var(--text-basic-color)',
  toastr_icon_basic_background_color: 'var(--background-basic-color-1)',
  toastr_icon_basic_color: 'var(--text-basic-color)',
  toastr_destroyable_basic_hover_background_color: 'var(--background-basic-color-1)',
  toastr_destroyable_basic_hover_border_color: 'var(--border-basic-color-3)',

  toastr_primary_background_color: 'var(--color-primary-default)',
  toastr_primary_border_color: 'var(--color-primary-default)',
  toastr_primary_text_color: 'var(--text-control-color)',
  toastr_icon_primary_background_color: 'var(--background-basic-color-1)',
  toastr_icon_primary_color: 'var(--color-primary-default)',
  toastr_destroyable_primary_hover_background_color: 'var(--color-primary-hover)',
  toastr_destroyable_primary_hover_border_color: 'var(--color-primary-hover)',

  toastr_success_background_color: 'var(--color-success-default)',
  toastr_success_border_color: 'var(--color-success-default)',
  toastr_success_text_color: 'var(--text-control-color)',
  toastr_icon_success_background_color: 'var(--background-basic-color-1)',
  toastr_icon_success_color: 'var(--color-success-default)',
  toastr_destroyable_success_hover_background_color: 'var(--color-success-hover)',
  toastr_destroyable_success_hover_border_color: 'var(--color-success-hover)',

  toastr_info_background_color: 'var(--color-info-default)',
  toastr_info_border_color: 'var(--color-info-default)',
  toastr_info_text_color: 'var(--text-control-color)',
  toastr_icon_info_background_color: 'var(--background-basic-color-1)',
  toastr_icon_info_color: 'var(--color-info-default)',
  toastr_destroyable_info_hover_background_color: 'var(--color-info-hover)',
  toastr_destroyable_info_hover_border_color: 'var(--color-info-hover)',

  toastr_warning_background_color: 'var(--color-warning-default)',
  toastr_warning_border_color: 'var(--color-warning-default)',
  toastr_warning_text_color: 'var(--text-control-color)',
  toastr_icon_warning_background_color: 'var(--background-basic-color-1)',
  toastr_icon_warning_color: 'var(--color-warning-default)',
  toastr_destroyable_warning_hover_background_color: 'var(--color-warning-hover)',
  toastr_destroyable_warning_hover_border_color: 'var(--color-warning-hover)',

  toastr_danger_background_color: 'var(--color-danger-default)',
  toastr_danger_border_color: 'var(--color-danger-default)',
  toastr_danger_text_color: 'var(--text-control-color)',
  toastr_icon_danger_background_color: 'var(--background-basic-color-1)',
  toastr_icon_danger_color: 'var(--color-danger-default)',
  toastr_destroyable_danger_hover_background_color: 'var(--color-danger-hover)',
  toastr_destroyable_danger_hover_border_color: 'var(--color-danger-hover)',

  toastr_control_background_color: 'var(--color-control-default)',
  toastr_control_border_color: 'var(--color-control-default)',
  toastr_control_text_color: 'var(--color-basic-800)',
  toastr_icon_control_background_color: 'var(--color-control-default)',
  toastr_icon_control_color: 'var(--color-basic-800)',
  toastr_destroyable_control_hover_background_color: 'var(--color-control-hover)',
  toastr_destroyable_control_hover_border_color: 'var(--color-control-hover)'
};
