import { NebularThemeButton } from '../types/nebular-theme';

const button_filled_primary_text_color = 'var(--text-control-color)';
const button_filled_success_text_color = 'var(--text-control-color)';
const button_filled_info_text_color = 'var(--text-control-color)';
const button_filled_warning_text_color = 'var(--text-control-color)';
const button_filled_danger_text_color = 'var(--text-control-color)';
const button_filled_control_text_color = 'var(--color-basic-800)';

export const DefaultThemeButton: NebularThemeButton = {
  button_cursor: 'pointer',
  button_outline_width: 'var(--outline-width)',
  button_outline_color: 'var(--outline-color)',
  button_text_font_family: 'var(--text-button-font-family)',
  button_text_font_weight: 'var(--text-button-font-weight)',
  button_disabled_cursor: 'not-allowed',

  button_tiny_text_font_size: 'var(--text-button-tiny-font-size)',
  button_tiny_text_line_height: 'var(--text-button-tiny-line-height)',
  button_tiny_icon_size: '0.75rem',
  button_tiny_icon_vertical_margin: '-0.125rem',
  button_tiny_icon_offset: '0.375rem',

  button_small_text_font_size: 'var(--text-button-small-font-size)',
  button_small_text_line_height: 'var(--text-button-small-line-height)',
  button_small_icon_size: '1rem',
  button_small_icon_vertical_margin: '-0.125rem',
  button_small_icon_offset: '0.375rem',

  button_medium_text_font_size: 'var(--text-button-medium-font-size)',
  button_medium_text_line_height: 'var(--text-button-medium-line-height)',
  button_medium_icon_size: '1.25rem',
  button_medium_icon_vertical_margin: '-0.125rem',
  button_medium_icon_offset: '0.5rem',

  button_large_text_font_size: 'var(--text-button-large-font-size)',
  button_large_text_line_height: 'var(--text-button-large-line-height)',
  button_large_icon_size: '1.5rem',
  button_large_icon_vertical_margin: '-0.125rem',
  button_large_icon_offset: '0.75rem',

  button_giant_text_font_size: 'var(--text-button-giant-font-size)',
  button_giant_text_line_height: 'var(--text-button-giant-line-height)',
  button_giant_icon_size: '1.5rem',
  button_giant_icon_vertical_margin: '-0.125rem',
  button_giant_icon_offset: '0.75rem',

  button_rectangle_border_radius: 'var(--border-radius)',
  button_semiround_border_radius: '0.75rem',
  button_round_border_radius: '1.5rem',

  button_filled_border_style: 'solid',
  button_filled_border_width: '0.0625rem',
  button_filled_text_transform: 'uppercase',

  button_filled_tiny_padding: '0.3125rem 0.625rem',
  button_filled_small_padding: '0.4375rem 0.875rem',
  button_filled_medium_padding: '0.6875rem 1.125rem',
  button_filled_large_padding: '0.8125rem 1.125rem',
  button_filled_giant_padding: '0.9375rem 1.375rem',

  button_filled_basic_background_color: 'var(--color-basic-default)',
  button_filled_basic_border_color: 'var(--color-basic-default-border)',
  button_filled_basic_text_color: 'var(--color-basic-800)',
  button_filled_basic_focus_background_color: 'var(--color-basic-focus)',
  button_filled_basic_focus_border_color: 'var(--color-basic-focus-border)',
  button_filled_basic_hover_background_color: 'var(--color-basic-hover)',
  button_filled_basic_hover_border_color: 'var(--color-basic-hover-border)',
  button_filled_basic_active_background_color: 'var(--color-basic-active)',
  button_filled_basic_active_border_color: 'var(--color-basic-active-border)',
  button_filled_basic_disabled_background_color: 'var(--color-basic-disabled)',
  button_filled_basic_disabled_border_color: 'var(--color-basic-disabled-border)',
  button_filled_basic_disabled_text_color: 'var(--text-disabled-color)',

  button_filled_primary_background_color: 'var(--color-primary-default)',
  button_filled_primary_border_color: 'var(--color-primary-default-border)',
  button_filled_primary_text_color,
  button_filled_primary_focus_background_color: 'var(--color-primary-focus)',
  button_filled_primary_focus_border_color: 'var(--color-primary-focus-border)',
  button_filled_primary_hover_background_color: 'var(--color-primary-hover)',
  button_filled_primary_hover_border_color: 'var(--color-primary-hover-border)',
  button_filled_primary_active_background_color: 'var(--color-primary-active)',
  button_filled_primary_active_border_color: 'var(--color-primary-active-border)',
  button_filled_primary_disabled_background_color: 'var(--color-primary-disabled)',
  button_filled_primary_disabled_border_color: 'var(--color-primary-disabled-border)',
  button_filled_primary_disabled_text_color: 'var(--text-disabled-color)',

  button_filled_success_background_color: 'var(--color-success-default)',
  button_filled_success_border_color: 'var(--color-success-default-border)',
  button_filled_success_text_color,
  button_filled_success_focus_background_color: 'var(--color-success-focus)',
  button_filled_success_focus_border_color: 'var(--color-success-focus-border)',
  button_filled_success_hover_background_color: 'var(--color-success-hover)',
  button_filled_success_hover_border_color: 'var(--color-success-hover-border)',
  button_filled_success_active_background_color: 'var(--color-success-active)',
  button_filled_success_active_border_color: 'var(--color-success-active-border)',
  button_filled_success_disabled_background_color: 'var(--color-success-disabled)',
  button_filled_success_disabled_border_color: 'var(--color-success-disabled-border)',
  button_filled_success_disabled_text_color: 'var(--text-disabled-color)',

  button_filled_info_background_color: 'var(--color-info-default)',
  button_filled_info_border_color: 'var(--color-info-default-border)',
  button_filled_info_text_color,
  button_filled_info_focus_background_color: 'var(--color-info-focus)',
  button_filled_info_focus_border_color: 'var(--color-info-focus-border)',
  button_filled_info_hover_background_color: 'var(--color-info-hover)',
  button_filled_info_hover_border_color: 'var(--color-info-hover-border)',
  button_filled_info_active_background_color: 'var(--color-info-active)',
  button_filled_info_active_border_color: 'var(--color-info-active-border)',
  button_filled_info_disabled_background_color: 'var(--color-info-disabled)',
  button_filled_info_disabled_border_color: 'var(--color-info-disabled-border)',
  button_filled_info_disabled_text_color: 'var(--text-disabled-color)',

  button_filled_warning_background_color: 'var(--color-warning-default)',
  button_filled_warning_border_color: 'var(--color-warning-default-border)',
  button_filled_warning_text_color,
  button_filled_warning_focus_background_color: 'var(--color-warning-focus)',
  button_filled_warning_focus_border_color: 'var(--color-warning-focus-border)',
  button_filled_warning_hover_background_color: 'var(--color-warning-hover)',
  button_filled_warning_hover_border_color: 'var(--color-warning-hover-border)',
  button_filled_warning_active_background_color: 'var(--color-warning-active)',
  button_filled_warning_active_border_color: 'var(--color-warning-active-border)',
  button_filled_warning_disabled_background_color: 'var(--color-warning-disabled)',
  button_filled_warning_disabled_border_color: 'var(--color-warning-disabled-border)',
  button_filled_warning_disabled_text_color: 'var(--text-disabled-color)',

  button_filled_danger_background_color: 'var(--color-danger-default)',
  button_filled_danger_border_color: 'var(--color-danger-default-border)',
  button_filled_danger_text_color,
  button_filled_danger_focus_background_color: 'var(--color-danger-focus)',
  button_filled_danger_focus_border_color: 'var(--color-danger-focus-border)',
  button_filled_danger_hover_background_color: 'var(--color-danger-hover)',
  button_filled_danger_hover_border_color: 'var(--color-danger-hover-border)',
  button_filled_danger_active_background_color: 'var(--color-danger-active)',
  button_filled_danger_active_border_color: 'var(--color-danger-active-border)',
  button_filled_danger_disabled_background_color: 'var(--color-danger-disabled)',
  button_filled_danger_disabled_border_color: 'var(--color-danger-disabled-border)',
  button_filled_danger_disabled_text_color: 'var(--text-disabled-color)',

  button_filled_control_background_color: 'var(--color-control-default)',
  button_filled_control_border_color: 'var(--color-control-default-border)',
  button_filled_control_text_color,
  button_filled_control_focus_background_color: 'var(--color-control-focus)',
  button_filled_control_focus_border_color: 'var(--color-control-focus-border)',
  button_filled_control_hover_background_color: 'var(--color-control-hover)',
  button_filled_control_hover_border_color: 'var(--color-control-hover-border)',
  button_filled_control_active_background_color: 'var(--color-control-active)',
  button_filled_control_active_border_color: 'var(--color-control-active-border)',
  button_filled_control_disabled_background_color: 'var(--color-control-disabled)',
  button_filled_control_disabled_border_color: 'var(--color-control-disabled-border)',
  button_filled_control_disabled_text_color: 'var(--text-disabled-color)',

  button_outline_border_style: 'solid',
  button_outline_border_width: '0.0625rem',
  button_outline_text_transform: 'uppercase',
  button_outline_focus_inset_shadow_length: '0 0 0 100vmax',

  button_outline_tiny_padding: '0.3125rem 0.625rem',
  button_outline_small_padding: '0.4375rem 0.875rem',
  button_outline_medium_padding: '0.6875rem 1.125rem',
  button_outline_large_padding: '0.8125rem 1.125rem',
  button_outline_giant_padding: '0.9375rem 1.375rem',

  button_outline_basic_background_color: 'var(--color-basic-transparent-default)',
  button_outline_basic_border_color: 'var(--color-basic-transparent-default-border)',
  button_outline_basic_text_color: 'var(--text-hint-color)',
  button_outline_basic_focus_background_color: 'var(--color-basic-transparent-focus)',
  button_outline_basic_focus_border_color: 'var(--color-basic-transparent-focus-border)',
  button_outline_basic_focus_text_color: 'var(--text-hint-color)',
  button_outline_basic_hover_background_color: 'var(--color-basic-transparent-hover)',
  button_outline_basic_hover_border_color: 'var(--color-basic-transparent-hover-border)',
  button_outline_basic_hover_text_color: 'var(--text-hint-color)',
  button_outline_basic_active_background_color: 'var(--color-basic-transparent-active)',
  button_outline_basic_active_border_color: 'var(--color-basic-transparent-active-border)',
  button_outline_basic_active_text_color: 'var(--text-hint-color)',
  button_outline_basic_disabled_background_color: 'var(--color-basic-transparent-disabled)',
  button_outline_basic_disabled_border_color: 'var(--color-basic-transparent-disabled-border)',
  button_outline_basic_disabled_text_color: 'var(--text-disabled-color)',

  button_outline_primary_background_color: 'var(--color-primary-transparent-default)',
  button_outline_primary_border_color: 'var(--color-primary-transparent-default-border)',
  button_outline_primary_text_color: 'var(--text-primary-color)',
  button_outline_primary_focus_background_color: 'var(--color-primary-transparent-focus)',
  button_outline_primary_focus_border_color: 'var(--color-primary-transparent-focus-border)',
  button_outline_primary_focus_text_color: 'var(--text-primary-color)',
  button_outline_primary_hover_background_color: 'var(--color-primary-transparent-hover)',
  button_outline_primary_hover_border_color: 'var(--color-primary-transparent-hover-border)',
  button_outline_primary_hover_text_color: 'var(--text-primary-color)',
  button_outline_primary_active_background_color: 'var(--color-primary-transparent-active)',
  button_outline_primary_active_border_color: 'var(--color-primary-transparent-active-border)',
  button_outline_primary_active_text_color: 'var(--text-primary-color)',
  button_outline_primary_disabled_background_color: 'var(--color-primary-transparent-disabled)',
  button_outline_primary_disabled_border_color: 'var(--color-primary-transparent-disabled-border)',
  button_outline_primary_disabled_text_color: 'var(--text-disabled-color)',

  button_outline_success_background_color: 'var(--color-success-transparent-default)',
  button_outline_success_border_color: 'var(--color-success-transparent-default-border)',
  button_outline_success_text_color: 'var(--text-success-color)',
  button_outline_success_focus_background_color: 'var(--color-success-transparent-focus)',
  button_outline_success_focus_border_color: 'var(--color-success-transparent-focus-border)',
  button_outline_success_focus_text_color: 'var(--text-success-color)',
  button_outline_success_hover_background_color: 'var(--color-success-transparent-hover)',
  button_outline_success_hover_border_color: 'var(--color-success-transparent-hover-border)',
  button_outline_success_hover_text_color: 'var(--text-success-color)',
  button_outline_success_active_background_color: 'var(--color-success-transparent-active)',
  button_outline_success_active_border_color: 'var(--color-success-transparent-active-border)',
  button_outline_success_active_text_color: 'var(--text-success-color)',
  button_outline_success_disabled_background_color: 'var(--color-success-transparent-disabled)',
  button_outline_success_disabled_border_color: 'var(--color-success-transparent-disabled-border)',
  button_outline_success_disabled_text_color: 'var(--text-disabled-color)',

  button_outline_info_background_color: 'var(--color-info-transparent-default)',
  button_outline_info_border_color: 'var(--color-info-transparent-default-border)',
  button_outline_info_text_color: 'var(--text-info-color)',
  button_outline_info_focus_background_color: 'var(--color-info-transparent-focus)',
  button_outline_info_focus_border_color: 'var(--color-info-transparent-focus-border)',
  button_outline_info_focus_text_color: 'var(--text-info-color)',
  button_outline_info_hover_background_color: 'var(--color-info-transparent-hover)',
  button_outline_info_hover_border_color: 'var(--color-info-transparent-hover-border)',
  button_outline_info_hover_text_color: 'var(--text-info-color)',
  button_outline_info_active_background_color: 'var(--color-info-transparent-active)',
  button_outline_info_active_border_color: 'var(--color-info-transparent-active-border)',
  button_outline_info_active_text_color: 'var(--text-info-color)',
  button_outline_info_disabled_background_color: 'var(--color-info-transparent-disabled)',
  button_outline_info_disabled_border_color: 'var(--color-info-transparent-disabled-border)',
  button_outline_info_disabled_text_color: 'var(--text-disabled-color)',

  button_outline_warning_background_color: 'var(--color-warning-transparent-default)',
  button_outline_warning_border_color: 'var(--color-warning-transparent-default-border)',
  button_outline_warning_text_color: 'var(--text-warning-color)',
  button_outline_warning_focus_background_color: 'var(--color-warning-transparent-focus)',
  button_outline_warning_focus_border_color: 'var(--color-warning-transparent-focus-border)',
  button_outline_warning_focus_text_color: 'var(--text-warning-color)',
  button_outline_warning_hover_background_color: 'var(--color-warning-transparent-hover)',
  button_outline_warning_hover_border_color: 'var(--color-warning-transparent-hover-border)',
  button_outline_warning_hover_text_color: 'var(--text-warning-color)',
  button_outline_warning_active_background_color: 'var(--color-warning-transparent-active)',
  button_outline_warning_active_border_color: 'var(--color-warning-transparent-active-border)',
  button_outline_warning_active_text_color: 'var(--text-warning-color)',
  button_outline_warning_disabled_background_color: 'var(--color-warning-transparent-disabled)',
  button_outline_warning_disabled_border_color: 'var(--color-warning-transparent-disabled-border)',
  button_outline_warning_disabled_text_color: 'var(--text-disabled-color)',

  button_outline_danger_background_color: 'var(--color-danger-transparent-default)',
  button_outline_danger_border_color: 'var(--color-danger-transparent-default-border)',
  button_outline_danger_text_color: 'var(--text-danger-color)',
  button_outline_danger_focus_background_color: 'var(--color-danger-transparent-focus)',
  button_outline_danger_focus_border_color: 'var(--color-danger-transparent-focus-border)',
  button_outline_danger_focus_text_color: 'var(--text-danger-color)',
  button_outline_danger_hover_background_color: 'var(--color-danger-transparent-hover)',
  button_outline_danger_hover_border_color: 'var(--color-danger-transparent-hover-border)',
  button_outline_danger_hover_text_color: 'var(--text-danger-color)',
  button_outline_danger_active_background_color: 'var(--color-danger-transparent-active)',
  button_outline_danger_active_border_color: 'var(--color-danger-transparent-active-border)',
  button_outline_danger_active_text_color: 'var(--text-danger-color)',
  button_outline_danger_disabled_background_color: 'var(--color-danger-transparent-disabled)',
  button_outline_danger_disabled_border_color: 'var(--color-danger-transparent-disabled-border)',
  button_outline_danger_disabled_text_color: 'var(--text-disabled-color)',

  button_outline_control_background_color: 'var(--color-control-transparent-default)',
  button_outline_control_border_color: 'var(--color-control-transparent-default-border)',
  button_outline_control_text_color: 'var(--text-control-color)',
  button_outline_control_focus_background_color: 'var(--color-control-transparent-focus)',
  button_outline_control_focus_border_color: 'var(--color-control-transparent-focus-border)',
  button_outline_control_focus_text_color: 'var(--text-control-color)',
  button_outline_control_hover_background_color: 'var(--color-control-transparent-hover)',
  button_outline_control_hover_border_color: 'var(--color-control-transparent-hover-border)',
  button_outline_control_hover_text_color: 'var(--text-control-color)',
  button_outline_control_active_background_color: 'var(--color-control-transparent-active)',
  button_outline_control_active_border_color: 'var(--color-control-transparent-active-border)',
  button_outline_control_active_text_color: 'var(--text-control-color)',
  button_outline_control_disabled_background_color: 'var(--color-control-transparent-disabled)',
  button_outline_control_disabled_border_color: 'var(--color-control-transparent-disabled-border)',
  button_outline_control_disabled_text_color: 'var(--text-disabled-color)',

  button_ghost_background_color: 'transparent',
  button_ghost_border_color: 'transparent',
  button_ghost_border_style: 'solid',
  button_ghost_border_width: '0.0625rem',
  button_ghost_text_transform: 'uppercase',
  button_ghost_focus_inset_shadow_length: '0 0 0 100vmax',

  button_ghost_tiny_padding: '0.3125rem 0.625rem',
  button_ghost_small_padding: '0.4375rem 0.875rem',
  button_ghost_medium_padding: '0.6875rem 1.125rem',
  button_ghost_large_padding: '0.8125rem 1.125rem',
  button_ghost_giant_padding: '0.9375rem 1.375rem',

  button_ghost_basic_text_color: 'var(--color-basic-600)',
  button_ghost_basic_focus_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_basic_focus_border_color: 'var(--color-basic-transparent-500)',
  button_ghost_basic_focus_text_color: 'var(--color-basic-600)',
  button_ghost_basic_hover_background_color: 'var(--color-basic-transparent-100)',
  button_ghost_basic_hover_border_color: 'transparent',
  button_ghost_basic_hover_text_color: 'var(--color-basic-600)',
  button_ghost_basic_active_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_basic_active_border_color: 'transparent',
  button_ghost_basic_active_text_color: 'var(--color-basic-600)',
  button_ghost_basic_disabled_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_basic_disabled_border_color: 'transparent',
  button_ghost_basic_disabled_text_color: 'var(--text-disabled-color)',

  button_ghost_primary_text_color: 'var(--text-primary-color)',
  button_ghost_primary_focus_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_primary_focus_border_color: 'var(--color-basic-transparent-500)',
  button_ghost_primary_focus_text_color: 'var(--text-primary-color)',
  button_ghost_primary_hover_background_color: 'var(--color-basic-transparent-100)',
  button_ghost_primary_hover_border_color: 'transparent',
  button_ghost_primary_hover_text_color: 'var(--text-primary-color)',
  button_ghost_primary_active_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_primary_active_border_color: 'transparent',
  button_ghost_primary_active_text_color: 'var(--text-primary-color)',
  button_ghost_primary_disabled_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_primary_disabled_border_color: 'transparent',
  button_ghost_primary_disabled_text_color: 'var(--text-disabled-color)',

  button_ghost_success_text_color: 'var(--text-success-color)',
  button_ghost_success_focus_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_success_focus_border_color: 'var(--color-basic-transparent-500)',
  button_ghost_success_focus_text_color: 'var(--text-success-color)',
  button_ghost_success_hover_background_color: 'var(--color-basic-transparent-100)',
  button_ghost_success_hover_border_color: 'transparent',
  button_ghost_success_hover_text_color: 'var(--text-success-color)',
  button_ghost_success_active_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_success_active_border_color: 'transparent',
  button_ghost_success_active_text_color: 'var(--text-success-color)',
  button_ghost_success_disabled_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_success_disabled_border_color: 'transparent',
  button_ghost_success_disabled_text_color: 'var(--text-disabled-color)',

  button_ghost_info_text_color: 'var(--text-info-color)',
  button_ghost_info_focus_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_info_focus_border_color: 'var(--color-basic-transparent-500)',
  button_ghost_info_focus_text_color: 'var(--text-info-color)',
  button_ghost_info_hover_background_color: 'var(--color-basic-transparent-100)',
  button_ghost_info_hover_border_color: 'transparent',
  button_ghost_info_hover_text_color: 'var(--text-info-color)',
  button_ghost_info_active_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_info_active_border_color: 'transparent',
  button_ghost_info_active_text_color: 'var(--text-info-color)',
  button_ghost_info_disabled_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_info_disabled_border_color: 'transparent',
  button_ghost_info_disabled_text_color: 'var(--text-disabled-color)',

  button_ghost_warning_text_color: 'var(--text-warning-color)',
  button_ghost_warning_focus_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_warning_focus_border_color: 'var(--color-basic-transparent-500)',
  button_ghost_warning_focus_text_color: 'var(--text-warning-color)',
  button_ghost_warning_hover_background_color: 'var(--color-basic-transparent-100)',
  button_ghost_warning_hover_border_color: 'transparent',
  button_ghost_warning_hover_text_color: 'var(--text-warning-color)',
  button_ghost_warning_active_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_warning_active_border_color: 'transparent',
  button_ghost_warning_active_text_color: 'var(--text-warning-color)',
  button_ghost_warning_disabled_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_warning_disabled_border_color: 'transparent',
  button_ghost_warning_disabled_text_color: 'var(--text-disabled-color)',

  button_ghost_danger_text_color: 'var(--text-danger-color)',
  button_ghost_danger_focus_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_danger_focus_border_color: 'var(--color-basic-transparent-500)',
  button_ghost_danger_focus_text_color: 'var(--text-danger-color)',
  button_ghost_danger_hover_background_color: 'var(--color-basic-transparent-100)',
  button_ghost_danger_hover_border_color: 'transparent',
  button_ghost_danger_hover_text_color: 'var(--text-danger-color)',
  button_ghost_danger_active_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_danger_active_border_color: 'transparent',
  button_ghost_danger_active_text_color: 'var(--text-danger-color)',
  button_ghost_danger_disabled_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_danger_disabled_border_color: 'transparent',
  button_ghost_danger_disabled_text_color: 'var(--text-disabled-color)',

  button_ghost_control_text_color: 'var(--color-basic-100)',
  button_ghost_control_focus_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_control_focus_border_color: 'var(--color-basic-transparent-500)',
  button_ghost_control_focus_text_color: 'var(--color-basic-100)',
  button_ghost_control_hover_background_color: 'var(--color-basic-transparent-100)',
  button_ghost_control_hover_border_color: 'transparent',
  button_ghost_control_hover_text_color: 'var(--color-basic-100)',
  button_ghost_control_active_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_control_active_border_color: 'transparent',
  button_ghost_control_active_text_color: 'var(--color-basic-100)',
  button_ghost_control_disabled_background_color: 'var(--color-basic-transparent-200)',
  button_ghost_control_disabled_border_color: 'transparent',
  button_ghost_control_disabled_text_color: 'var(--text-disabled-color)',

  button_hero_border_color: 'transparent',
  button_hero_border_style: 'solid',
  button_hero_border_width: '0',
  button_hero_text_transform: 'uppercase',

  button_hero_tiny_padding: '0.375rem 0.6875rem',
  button_hero_small_padding: '0.5rem 0.9375rem',
  button_hero_medium_padding: '0.75rem 1.1875rem',
  button_hero_large_padding: '0.875rem 1.1875rem',
  button_hero_giant_padding: '1rem 1.4375rem',

  button_hero_shadow: '0 0 transparent',
  button_hero_text_shadow: 'var(--shadow)',
  button_hero_bevel_size: '0 0 0 0',
  button_hero_glow_size: '0 0 0 0',
  button_hero_outline_color: 'var(--outline-color)',
  button_hero_outline_width: 'var(--outline-width)',

  button_hero_basic_text_color: 'var(--color-basic-600)',
  button_hero_basic_bevel_color: 'var(--color-basic-600)',
  button_hero_basic_glow_color: 'var(--color-basic-700)',
  button_hero_basic_left_background_color: 'var(--color-basic-200)',
  button_hero_basic_right_background_color: 'var(--color-basic-default)',
  button_hero_basic_focus_left_background_color: 'var(--color-basic-300)',
  button_hero_basic_focus_right_background_color: 'var(--color-basic-focus)',
  button_hero_basic_hover_left_background_color: 'var(--color-basic-100)',
  button_hero_basic_hover_right_background_color: 'var(--color-basic-hover)',
  button_hero_basic_active_left_background_color: 'var(--color-basic-300)',
  button_hero_basic_active_right_background_color: 'var(--color-basic-active)',
  button_hero_basic_disabled_background_color: 'var(--color-basic-disabled)',
  button_hero_basic_disabled_text_color: 'var(--text-disabled-color)',

  button_hero_primary_text_color: 'var(--text-control-color)',
  button_hero_primary_bevel_color: 'var(--color-primary-600)',
  button_hero_primary_glow_color: 'var(--color-primary-700)',
  button_hero_primary_left_background_color: 'var(--color-primary-400)',
  button_hero_primary_right_background_color: 'var(--color-primary-default)',
  button_hero_primary_focus_left_background_color: 'var(--color-primary-500)',
  button_hero_primary_focus_right_background_color: 'var(--color-primary-focus)',
  button_hero_primary_hover_left_background_color: 'var(--color-primary-300)',
  button_hero_primary_hover_right_background_color: 'var(--color-primary-hover)',
  button_hero_primary_active_left_background_color: 'var(--color-primary-500)',
  button_hero_primary_active_right_background_color: 'var(--color-primary-active)',
  button_hero_primary_disabled_background_color: 'var(--color-primary-disabled)',
  button_hero_primary_disabled_text_color: 'var(--text-disabled-color)',

  button_hero_success_text_color: 'var(--text-control-color)',
  button_hero_success_bevel_color: 'var(--color-success-600)',
  button_hero_success_glow_color: 'var(--color-success-700)',
  button_hero_success_left_background_color: 'var(--color-success-400)',
  button_hero_success_right_background_color: 'var(--color-success-default)',
  button_hero_success_focus_left_background_color: 'var(--color-success-500)',
  button_hero_success_focus_right_background_color: 'var(--color-success-focus)',
  button_hero_success_hover_left_background_color: 'var(--color-success-300)',
  button_hero_success_hover_right_background_color: 'var(--color-success-hover)',
  button_hero_success_active_left_background_color: 'var(--color-success-500)',
  button_hero_success_active_right_background_color: 'var(--color-success-active)',
  button_hero_success_disabled_background_color: 'var(--color-success-disabled)',
  button_hero_success_disabled_text_color: 'var(--text-disabled-color)',

  button_hero_info_text_color: 'var(--text-control-color)',
  button_hero_info_bevel_color: 'var(--color-info-600)',
  button_hero_info_glow_color: 'var(--color-info-700)',
  button_hero_info_left_background_color: 'var(--color-info-400)',
  button_hero_info_right_background_color: 'var(--color-info-default)',
  button_hero_info_focus_left_background_color: 'var(--color-info-500)',
  button_hero_info_focus_right_background_color: 'var(--color-info-focus)',
  button_hero_info_hover_left_background_color: 'var(--color-info-300)',
  button_hero_info_hover_right_background_color: 'var(--color-info-hover)',
  button_hero_info_active_left_background_color: 'var(--color-info-500)',
  button_hero_info_active_right_background_color: 'var(--color-info-active)',
  button_hero_info_disabled_background_color: 'var(--color-info-disabled)',
  button_hero_info_disabled_text_color: 'var(--text-disabled-color)',

  button_hero_warning_text_color: 'var(--text-control-color)',
  button_hero_warning_bevel_color: 'var(--color-warning-600)',
  button_hero_warning_glow_color: 'var(--color-warning-700)',
  button_hero_warning_left_background_color: 'var(--color-warning-400)',
  button_hero_warning_right_background_color: 'var(--color-warning-default)',
  button_hero_warning_focus_left_background_color: 'var(--color-warning-500)',
  button_hero_warning_focus_right_background_color: 'var(--color-warning-focus)',
  button_hero_warning_hover_left_background_color: 'var(--color-warning-300)',
  button_hero_warning_hover_right_background_color: 'var(--color-warning-hover)',
  button_hero_warning_active_left_background_color: 'var(--color-warning-500)',
  button_hero_warning_active_right_background_color: 'var(--color-warning-active)',
  button_hero_warning_disabled_background_color: 'var(--color-warning-disabled)',
  button_hero_warning_disabled_text_color: 'var(--text-disabled-color)',

  button_hero_danger_text_color: 'var(--text-control-color)',
  button_hero_danger_bevel_color: 'var(--color-danger-600)',
  button_hero_danger_glow_color: 'var(--color-danger-700)',
  button_hero_danger_left_background_color: 'var(--color-danger-400)',
  button_hero_danger_right_background_color: 'var(--color-danger-default)',
  button_hero_danger_focus_left_background_color: 'var(--color-danger-500)',
  button_hero_danger_focus_right_background_color: 'var(--color-danger-focus)',
  button_hero_danger_hover_left_background_color: 'var(--color-danger-300)',
  button_hero_danger_hover_right_background_color: 'var(--color-danger-hover)',
  button_hero_danger_active_left_background_color: 'var(--color-danger-500)',
  button_hero_danger_active_right_background_color: 'var(--color-danger-active)',
  button_hero_danger_disabled_background_color: 'var(--color-danger-disabled)',
  button_hero_danger_disabled_text_color: 'var(--text-disabled-color)',

  button_hero_control_text_color: 'var(--color-basic-800)',
  button_hero_control_bevel_color: 'var(--color-basic-600)',
  button_hero_control_glow_color: 'var(--color-basic-700)',
  button_hero_control_left_background_color: 'var(--color-control-default)',
  button_hero_control_right_background_color: 'var(--color-control-default)',
  button_hero_control_focus_left_background_color: 'var(--color-basic-200)',
  button_hero_control_focus_right_background_color: 'var(--color-control-focus)',
  button_hero_control_hover_left_background_color: 'var(--color-basic-100)',
  button_hero_control_hover_right_background_color: 'var(--color-control-hover)',
  button_hero_control_active_left_background_color: 'var(--color-basic-200)',
  button_hero_control_active_right_background_color: 'var(--color-control-active)',
  button_hero_control_disabled_background_color: 'var(--color-basic-transparent-300)',
  button_hero_control_disabled_text_color: 'var(--text-disabled-color)',

  button_group_filled_button_basic_text_color: 'var(--text-hint-color)',
  button_group_filled_button_primary_text_color: 'var(--button-filled-primary-text-color)',
  button_group_filled_button_success_text_color: 'var(--button-filled-success-text-color)',
  button_group_filled_button_info_text_color: 'var(--button-filled-info-text-color)',
  button_group_filled_button_warning_text_color: 'var(--button-filled-warning-text-color)',
  button_group_filled_button_danger_text_color: 'var(--button-filled-danger-text-color)',
  button_group_filled_button_control_text_color: 'var(--button-filled-control-text-color)',

  button_group_filled_basic_divider_color: 'var(--color-basic-focus-border)',
  button_group_filled_primary_divider_color: 'var(--color-primary-focus)',
  button_group_filled_success_divider_color: 'var(--color-success-focus)',
  button_group_filled_info_divider_color: 'var(--color-info-focus)',
  button_group_filled_warning_divider_color: 'var(--color-warning-focus)',
  button_group_filled_danger_divider_color: 'var(--color-danger-focus)',
  button_group_filled_control_divider_color: 'var(--color-control-focus)',

  button_group_ghost_divider_color: 'var(--color-basic-focus-border)',

  icon_button_filled_tiny_padding: '0.4375rem 0.3125rem',
  icon_button_filled_small_padding: '0.5625rem 0.4375rem',
  icon_button_filled_medium_padding: '0.6875rem 0.5625rem',
  icon_button_filled_large_padding: '0.8125rem 0.6875rem',
  icon_button_filled_giant_padding: '1.0625rem 0.9375rem',

  icon_button_outline_tiny_padding: '0.4375rem 0.3125rem',
  icon_button_outline_small_padding: '0.5625rem 0.4375rem',
  icon_button_outline_medium_padding: '0.6875rem 0.5625rem',
  icon_button_outline_large_padding: '0.8125rem 0.6875rem',
  icon_button_outline_giant_padding: '1.0625rem 0.9375rem',

  icon_button_ghost_tiny_padding: '0.4375rem 0.3125rem',
  icon_button_ghost_small_padding: '0.5625rem 0.4375rem',
  icon_button_ghost_medium_padding: '0.6875rem 0.5625rem',
  icon_button_ghost_large_padding: '0.8125rem 0.6875rem',
  icon_button_ghost_giant_padding: '1.0625rem 0.9375rem',

  icon_button_hero_tiny_padding: '0.5rem 0.375rem',
  icon_button_hero_small_padding: '0.5625rem 0.5rem',
  icon_button_hero_medium_padding: '0.75rem 0.5625rem',
  icon_button_hero_large_padding: '0.875rem 0.6875rem',
  icon_button_hero_giant_padding: '1.0625rem 1rem'
};
