import { NebularThemeInput } from '../types/nebular-theme';

export const DefaultThemeInput: NebularThemeInput = {
  input_border_style: 'solid',
  input_border_width: '1px',
  input_outline_color: 'var(--outline-color)',
  input_outline_width: 'var(--outline-width)',
  input_placeholder_text_font_family: 'var(--text-paragraph-font-family)',
  input_text_font_family: 'var(--text-subtitle-font-family)',

  input_basic_text_color: 'var(--text-basic-color)',
  input_basic_placeholder_text_color: 'var(--text-hint-color)',
  input_basic_background_color: 'var(--background-basic-color-2)',
  input_basic_border_color: 'var(--border-basic-color-4)',
  input_basic_focus_background_color: 'var(--background-basic-color-1)',
  input_basic_focus_border_color: 'var(--color-primary-default-border)',
  input_basic_hover_background_color: 'var(--background-basic-color-3)',
  input_basic_hover_border_color: 'var(--border-basic-color-4)',
  input_basic_disabled_background_color: 'var(--background-basic-color-2)',
  input_basic_disabled_border_color: 'var(--border-basic-color-4)',
  input_basic_disabled_text_color: 'var(--text-disabled-color)',
  input_basic_disabled_placeholder_text_color: 'var(--text-disabled-color)',

  input_primary_text_color: 'var(--text-basic-color)',
  input_primary_placeholder_text_color: 'var(--text-hint-color)',
  input_primary_background_color: 'var(--background-basic-color-2)',
  input_primary_border_color: 'var(--color-primary-default)',
  input_primary_focus_background_color: 'var(--background-basic-color-1)',
  input_primary_focus_border_color: 'var(--color-primary-focus-border)',
  input_primary_hover_background_color: 'var(--background-basic-color-3)',
  input_primary_hover_border_color: 'var(--color-primary-hover-border)',
  input_primary_disabled_background_color: 'var(--background-basic-color-2)',
  input_primary_disabled_border_color: 'var(--border-basic-color-4)',
  input_primary_disabled_text_color: 'var(--text-disabled-color)',
  input_primary_disabled_placeholder_text_color: 'var(--text-disabled-color)',

  input_success_text_color: 'var(--text-basic-color)',
  input_success_placeholder_text_color: 'var(--text-hint-color)',
  input_success_background_color: 'var(--background-basic-color-2)',
  input_success_border_color: 'var(--color-success-default)',
  input_success_focus_background_color: 'var(--background-basic-color-1)',
  input_success_focus_border_color: 'var(--color-success-focus-border)',
  input_success_hover_background_color: 'var(--background-basic-color-3)',
  input_success_hover_border_color: 'var(--color-success-hover-border)',
  input_success_disabled_background_color: 'var(--background-basic-color-2)',
  input_success_disabled_border_color: 'var(--border-basic-color-4)',
  input_success_disabled_text_color: 'var(--text-disabled-color)',
  input_success_disabled_placeholder_text_color: 'var(--text-disabled-color)',

  input_info_text_color: 'var(--text-basic-color)',
  input_info_placeholder_text_color: 'var(--text-hint-color)',
  input_info_background_color: 'var(--background-basic-color-2)',
  input_info_border_color: 'var(--color-info-default)',
  input_info_focus_background_color: 'var(--background-basic-color-1)',
  input_info_focus_border_color: 'var(--color-info-focus-border)',
  input_info_hover_background_color: 'var(--background-basic-color-3)',
  input_info_hover_border_color: 'var(--color-info-hover-border)',
  input_info_disabled_background_color: 'var(--background-basic-color-2)',
  input_info_disabled_border_color: 'var(--border-basic-color-4)',
  input_info_disabled_text_color: 'var(--text-disabled-color)',
  input_info_disabled_placeholder_text_color: 'var(--text-disabled-color)',

  input_warning_text_color: 'var(--text-basic-color)',
  input_warning_placeholder_text_color: 'var(--text-hint-color)',
  input_warning_background_color: 'var(--background-basic-color-2)',
  input_warning_border_color: 'var(--color-warning-default)',
  input_warning_focus_background_color: 'var(--background-basic-color-1)',
  input_warning_focus_border_color: 'var(--color-warning-focus-border)',
  input_warning_hover_background_color: 'var(--background-basic-color-3)',
  input_warning_hover_border_color: 'var(--color-warning-hover-border)',
  input_warning_disabled_background_color: 'var(--background-basic-color-2)',
  input_warning_disabled_border_color: 'var(--border-basic-color-4)',
  input_warning_disabled_text_color: 'var(--text-disabled-color)',
  input_warning_disabled_placeholder_text_color: 'var(--text-disabled-color)',

  input_danger_text_color: 'var(--text-basic-color)',
  input_danger_placeholder_text_color: 'var(--text-hint-color)',
  input_danger_background_color: 'var(--background-basic-color-2)',
  input_danger_border_color: 'var(--color-danger-default)',
  input_danger_focus_background_color: 'var(--background-basic-color-1)',
  input_danger_focus_border_color: 'var(--color-danger-focus-border)',
  input_danger_hover_background_color: 'var(--background-basic-color-3)',
  input_danger_hover_border_color: 'var(--color-danger-hover-border)',
  input_danger_disabled_background_color: 'var(--background-basic-color-2)',
  input_danger_disabled_border_color: 'var(--border-basic-color-4)',
  input_danger_disabled_text_color: 'var(--text-disabled-color)',
  input_danger_disabled_placeholder_text_color: 'var(--text-disabled-color)',

  input_control_text_color: 'var(--text-control-color)',
  input_control_placeholder_text_color: 'var(--text-control-color)',
  input_control_background_color: 'var(--color-basic-control-transparent-300)',
  input_control_border_color: 'var(--color-basic-control-transparent-500)',
  input_control_focus_background_color: 'var(--color-basic-control-transparent-500)',
  input_control_focus_border_color: 'var(--color-control-transparent-focus-border)',
  input_control_hover_background_color: 'var(--color-basic-control-transparent-400)',
  input_control_hover_border_color: 'var(--color-control-transparent-hover-border)',
  input_control_disabled_background_color: 'var(--color-control-transparent-disabled)',
  input_control_disabled_border_color: 'var(--color-control-transparent-disabled-border)',
  input_control_disabled_text_color: 'var(--text-control-color)',
  input_control_disabled_placeholder_text_color: 'var(--text-control-color)',

  input_rectangle_border_radius: 'var(--border-radius)',
  input_semiround_border_radius: '0.75rem',
  input_round_border_radius: '1.5rem',

  input_tiny_text_font_size: 'var(--text-caption-2-font-size)',
  input_tiny_text_font_weight: 'var(--text-caption-2-font-weight)',
  input_tiny_text_line_height: 'var(--text-caption-2-line-height)',
  input_tiny_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  input_tiny_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  input_tiny_placeholder_text_line_height: 'var(--text-paragraph-line-height)',
  input_tiny_padding: '0.1875rem 1rem',
  input_tiny_max_width: '20rem',

  input_small_text_font_size: 'var(--text-subtitle-2-font-size)',
  input_small_text_font_weight: 'var(--text-subtitle-2-font-weight)',
  input_small_text_line_height: 'var(--text-subtitle-2-line-height)',
  input_small_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  input_small_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  input_small_placeholder_text_line_height: 'var(--text-paragraph-line-height)',
  input_small_padding: '0.1875rem 1rem',
  input_small_max_width: '20rem',

  input_medium_text_font_size: 'var(--text-subtitle-font-size)',
  input_medium_text_font_weight: 'var(--text-subtitle-font-weight)',
  input_medium_text_line_height: 'var(--text-subtitle-line-height)',
  input_medium_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  input_medium_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  input_medium_placeholder_text_line_height: 'var(--text-paragraph-line-height)',
  input_medium_padding: '0.4375rem 1rem',
  input_medium_max_width: '20rem',

  input_large_text_font_size: 'var(--text-subtitle-font-size)',
  input_large_text_font_weight: 'var(--text-subtitle-font-weight)',
  input_large_text_line_height: 'var(--text-subtitle-line-height)',
  input_large_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  input_large_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  input_large_placeholder_text_line_height: 'var(--text-paragraph-line-height)',
  input_large_padding: '0.6875rem 1rem',
  input_large_max_width: '30rem',

  input_giant_text_font_size: 'var(--text-heading-6-font-size)',
  input_giant_text_font_weight: 'var(--text-heading-6-font-weight)',
  input_giant_text_line_height: 'var(--text-heading-6-line-height)',
  input_giant_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  input_giant_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  input_giant_placeholder_text_line_height: 'var(--text-paragraph-line-height)',
  input_giant_padding: '0.9375rem 1rem',
  input_giant_max_width: '30rem'
};
