import { NebularThemeCard } from '../types/nebular-theme';

export const DefaultThemeCard: NebularThemeCard = {
  card_background_color: 'var(--background-basic-color-1)',
  card_text_color: 'var(--text-basic-color)',
  card_text_font_family: 'var(--text-paragraph-font-family)',
  card_text_font_size: 'var(--text-paragraph-font-size)',
  card_text_font_weight: 'var(--text-paragraph-font-weight)',
  card_text_line_height: 'var(--text-paragraph-line-height)',
  card_border_width: '0.0625rem',
  card_border_style: 'solid',
  card_border_color: 'var(--border-basic-color-4)',
  card_border_radius: 'var(--border-radius)',
  card_padding: '1rem 1.5rem',
  card_shadow: 'none',
  card_divider_color: 'var(--divider-color)',
  card_divider_style: 'var(--divider-style)',
  card_divider_width: 'var(--divider-width)',

  card_header_text_color: 'var(--text-basic-color)',
  card_header_text_font_family: 'var(--text-subtitle-font-family)',
  card_header_text_font_size: 'var(--text-subtitle-font-size)',
  card_header_text_font_weight: 'var(--text-subtitle-font-weight)',
  card_header_text_line_height: 'var(--text-subtitle-line-height)',
  card_header_basic_background_color: 'var(--background-basic-color-2)',
  card_header_basic_text_color: 'var(--text-basic-color)',
  card_header_primary_background_color: 'var(--color-primary-default)',
  card_header_primary_text_color: 'var(--text-control-color)',
  card_header_info_background_color: 'var(--color-info-default)',
  card_header_info_text_color: 'var(--text-control-color)',
  card_header_success_background_color: 'var(--color-success-default)',
  card_header_success_text_color: 'var(--text-control-color)',
  card_header_warning_background_color: 'var(--color-warning-default)',
  card_header_warning_text_color: 'var(--text-control-color)',
  card_header_danger_background_color: 'var(--color-danger-default)',
  card_header_danger_text_color: 'var(--text-control-color)',
  card_header_control_background_color: 'var(--color-control-default)',
  card_header_control_text_color: 'var(--color-basic-800)',

  card_height_tiny: '13.5rem',
  card_height_small: '21.1875rem',
  card_height_medium: '28.875rem',
  card_height_large: '36.5625rem',
  card_height_giant: '44.25rem',
  card_margin_bottom: '1.875rem',

  card_scrollbar_color: 'var(--scrollbar-color)',
  card_scrollbar_background_color: 'var(--scrollbar-background-color)',
  card_scrollbar_width: 'var(--scrollbar-width)',

  header_background_color: 'var(--background-basic-color-1)',
  header_text_color: 'var(--text-basic-color)',
  header_text_font_family: 'var(--text-paragraph-font-family)',
  header_text_font_size: 'var(--text-paragraph-font-size)',
  header_text_font_weight: 'var(--text-paragraph-font-weight)',
  header_text_line_height: 'var(--text-paragraph-line-height)',
  header_height: '4.75rem',
  header_padding: '1.25rem',
  header_shadow: 'var(--shadow)',

  footer_background_color: 'var(--background-basic-color-1)',
  footer_text_color: 'var(--text-basic-color)',
  footer_text_font_family: 'var(--text-paragraph-font-family)',
  footer_text_font_size: 'var(--text-paragraph-font-size)',
  footer_text_font_weight: 'var(--text-paragraph-font-weight)',
  footer_text_line_height: 'var(--text-paragraph-line-height)',
  footer_text_highlight_color: 'var(--color-primary-hover)',
  footer_height: '4.725rem',
  footer_padding: '1.25rem',
  footer_divider_color: 'var(--divider-color)',
  footer_divider_style: 'var(--divider-style)',
  footer_divider_width: 'var(--divider-width)',
  footer_shadow: 'var(--shadow)'
};
