import { NebularThemeSelect } from '../types/nebular-theme';

const select_outline_basic_border_color = 'var(--border-basic-color-4)';
const select_outline_primary_border_color = 'var(--color-primary-default)';
const select_outline_success_border_color = 'var(--color-success-default)';
const select_outline_info_border_color = 'var(--color-info-default)';
const select_outline_warning_border_color = 'var(--color-warning-default)';
const select_outline_danger_border_color = 'var(--color-danger-default)';
const select_outline_control_border_color = 'var(--color-basic-control-transparent-500)';

export const DefaultThemeSelect: NebularThemeSelect = {
  select_outline_tiny_padding: '0.1875rem 1rem',
  select_outline_small_padding: '0.1875rem 1rem',
  select_outline_medium_padding: '0.4375rem 1rem',
  select_outline_large_padding: '0.6875rem 1rem',
  select_outline_giant_padding: '0.9375rem 1rem',

  option_tiny_text_font_size: 'var(--text-caption-2-font-size)',
  option_tiny_text_font_weight: 'var(--text-caption-2-font-weight)',
  option_tiny_text_line_height: 'var(--text-caption-2-line-height)',
  option_tiny_padding: 'var(--select-outline-tiny-padding)',

  option_small_text_font_size: 'var(--text-subtitle-2-font-size)',
  option_small_text_font_weight: 'var(--text-subtitle-2-font-weight)',
  option_small_text_line_height: 'var(--text-subtitle-2-line-height)',
  option_small_padding: 'var(--select-outline-small-padding)',

  option_medium_text_font_size: 'var(--text-subtitle-font-size)',
  option_medium_text_font_weight: 'var(--text-subtitle-font-weight)',
  option_medium_text_line_height: 'var(--text-subtitle-line-height)',
  option_medium_padding: 'var(--select-outline-medium-padding)',

  option_large_text_font_size: 'var(--text-subtitle-font-size)',
  option_large_text_font_weight: 'var(--text-subtitle-font-weight)',
  option_large_text_line_height: 'var(--text-subtitle-line-height)',
  option_large_padding: 'var(--select-outline-large-padding)',

  option_giant_text_font_size: 'var(--text-heading-6-font-size)',
  option_giant_text_font_weight: 'var(--text-heading-6-font-weight)',
  option_giant_text_line_height: 'var(--text-heading-6-line-height)',
  option_giant_padding: 'var(--select-outline-giant-padding)',

  select_cursor: 'pointer',
  select_disabled_cursor: 'default',
  select_min_width: '13rem',
  select_outline_width: 'var(--outline-width)',
  select_outline_color: 'var(--outline-color)',
  select_icon_offset: '2rem',

  select_text_font_family: 'var(--text-subtitle-font-family)',
  select_placeholder_text_font_family: 'var(--text-paragraph-font-family)',

  select_tiny_text_font_size: 'var(--text-caption-2-font-size)',
  select_tiny_text_font_weight: 'var(--text-caption-2-font-weight)',
  select_tiny_text_line_height: 'var(--text-caption-2-line-height)',
  select_tiny_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  select_tiny_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  select_tiny_max_width: '20rem',

  select_small_text_font_size: 'var(--text-subtitle-2-font-size)',
  select_small_text_font_weight: 'var(--text-subtitle-2-font-weight)',
  select_small_text_line_height: 'var(--text-subtitle-2-line-height)',
  select_small_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  select_small_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  select_small_max_width: '20rem',

  select_medium_text_font_size: 'var(--text-subtitle-font-size)',
  select_medium_text_font_weight: 'var(--text-subtitle-font-weight)',
  select_medium_text_line_height: 'var(--text-subtitle-line-height)',
  select_medium_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  select_medium_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  select_medium_max_width: '20rem',

  select_large_text_font_size: 'var(--text-subtitle-font-size)',
  select_large_text_font_weight: 'var(--text-subtitle-font-weight)',
  select_large_text_line_height: 'var(--text-subtitle-line-height)',
  select_large_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  select_large_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  select_large_max_width: '30rem',

  select_giant_text_font_size: 'var(--text-heading-6-font-size)',
  select_giant_text_font_weight: 'var(--text-heading-6-font-weight)',
  select_giant_text_line_height: 'var(--text-heading-6-line-height)',
  select_giant_placeholder_text_font_size: 'var(--text-paragraph-font-size)',
  select_giant_placeholder_text_font_weight: 'var(--text-paragraph-font-weight)',
  select_giant_max_width: '30rem',

  select_rectangle_border_radius: 'var(--border-radius)',
  select_semiround_border_radius: '0.75rem',
  select_round_border_radius: '1.5rem',

  select_outline_border_style: 'solid',
  select_outline_border_width: '1px',

  select_outline_basic_icon_color: 'var(--text-hint-color)',
  select_outline_basic_text_color: 'var(--text-basic-color)',
  select_outline_basic_placeholder_text_color: 'var(--text-hint-color)',
  select_outline_basic_background_color: 'var(--background-basic-color-2)',
  select_outline_basic_border_color,
  select_outline_basic_focus_background_color: 'var(--background-basic-color-1)',
  select_outline_basic_focus_border_color: 'var(--color-primary-default)',
  select_outline_basic_hover_background_color: 'var(--background-basic-color-3)',
  select_outline_basic_hover_border_color: 'var(--border-basic-color-4)',
  select_outline_basic_disabled_background_color: 'var(--background-basic-color-2)',
  select_outline_basic_disabled_border_color: 'var(--border-basic-color-4)',
  select_outline_basic_disabled_icon_color: 'var(--text-disabled-color)',
  select_outline_basic_disabled_text_color: 'var(--text-disabled-color)',

  select_outline_primary_icon_color: 'var(--text-hint-color)',
  select_outline_primary_text_color: 'var(--text-basic-color)',
  select_outline_primary_placeholder_text_color: 'var(--text-hint-color)',
  select_outline_primary_background_color: 'var(--background-basic-color-2)',
  select_outline_primary_border_color,
  select_outline_primary_focus_background_color: 'var(--background-basic-color-1)',
  select_outline_primary_focus_border_color: 'var(--color-primary-focus)',
  select_outline_primary_hover_background_color: 'var(--background-basic-color-3)',
  select_outline_primary_hover_border_color: 'var(--color-primary-hover)',
  select_outline_primary_disabled_background_color: 'var(--background-basic-color-2)',
  select_outline_primary_disabled_border_color: 'var(--border-basic-color-4)',
  select_outline_primary_disabled_icon_color: 'var(--text-disabled-color)',
  select_outline_primary_disabled_text_color: 'var(--text-disabled-color)',

  select_outline_success_icon_color: 'var(--text-hint-color)',
  select_outline_success_text_color: 'var(--text-basic-color)',
  select_outline_success_placeholder_text_color: 'var(--text-hint-color)',
  select_outline_success_background_color: 'var(--background-basic-color-2)',
  select_outline_success_border_color,
  select_outline_success_focus_background_color: 'var(--background-basic-color-1)',
  select_outline_success_focus_border_color: 'var(--color-success-focus)',
  select_outline_success_hover_background_color: 'var(--background-basic-color-3)',
  select_outline_success_hover_border_color: 'var(--color-success-hover)',
  select_outline_success_disabled_background_color: 'var(--background-basic-color-2)',
  select_outline_success_disabled_border_color: 'var(--border-basic-color-4)',
  select_outline_success_disabled_icon_color: 'var(--text-disabled-color)',
  select_outline_success_disabled_text_color: 'var(--text-disabled-color)',

  select_outline_info_icon_color: 'var(--text-hint-color)',
  select_outline_info_text_color: 'var(--text-basic-color)',
  select_outline_info_placeholder_text_color: 'var(--text-hint-color)',
  select_outline_info_background_color: 'var(--background-basic-color-2)',
  select_outline_info_border_color,
  select_outline_info_focus_background_color: 'var(--background-basic-color-1)',
  select_outline_info_focus_border_color: 'var(--color-info-focus)',
  select_outline_info_hover_background_color: 'var(--background-basic-color-3)',
  select_outline_info_hover_border_color: 'var(--color-info-hover)',
  select_outline_info_disabled_background_color: 'var(--background-basic-color-2)',
  select_outline_info_disabled_border_color: 'var(--border-basic-color-4)',
  select_outline_info_disabled_icon_color: 'var(--text-disabled-color)',
  select_outline_info_disabled_text_color: 'var(--text-disabled-color)',

  select_outline_warning_icon_color: 'var(--text-hint-color)',
  select_outline_warning_text_color: 'var(--text-basic-color)',
  select_outline_warning_placeholder_text_color: 'var(--text-hint-color)',
  select_outline_warning_background_color: 'var(--background-basic-color-2)',
  select_outline_warning_border_color,
  select_outline_warning_focus_background_color: 'var(--background-basic-color-1)',
  select_outline_warning_focus_border_color: 'var(--color-warning-focus)',
  select_outline_warning_hover_background_color: 'var(--background-basic-color-3)',
  select_outline_warning_hover_border_color: 'var(--color-warning-hover)',
  select_outline_warning_disabled_background_color: 'var(--background-basic-color-2)',
  select_outline_warning_disabled_border_color: 'var(--border-basic-color-4)',
  select_outline_warning_disabled_icon_color: 'var(--text-disabled-color)',
  select_outline_warning_disabled_text_color: 'var(--text-disabled-color)',

  select_outline_danger_icon_color: 'var(--text-hint-color)',
  select_outline_danger_text_color: 'var(--text-basic-color)',
  select_outline_danger_placeholder_text_color: 'var(--text-hint-color)',
  select_outline_danger_background_color: 'var(--background-basic-color-2)',
  select_outline_danger_border_color,
  select_outline_danger_focus_background_color: 'var(--background-basic-color-1)',
  select_outline_danger_focus_border_color: 'var(--color-danger-focus)',
  select_outline_danger_hover_background_color: 'var(--background-basic-color-3)',
  select_outline_danger_hover_border_color: 'var(--color-danger-hover)',
  select_outline_danger_disabled_background_color: 'var(--background-basic-color-2)',
  select_outline_danger_disabled_border_color: 'var(--border-basic-color-4)',
  select_outline_danger_disabled_icon_color: 'var(--text-disabled-color)',
  select_outline_danger_disabled_text_color: 'var(--text-disabled-color)',

  select_outline_control_icon_color: 'var(--color-basic-100)',
  select_outline_control_text_color: 'var(--color-basic-100)',
  select_outline_control_placeholder_text_color: 'var(--color-basic-100)',
  select_outline_control_background_color: 'var(--color-basic-control-transparent-300)',
  select_outline_control_border_color,
  select_outline_control_focus_background_color: 'var(--color-basic-control-transparent-500)',
  select_outline_control_focus_border_color: 'var(--color-control-transparent-focus-border)',
  select_outline_control_hover_background_color: 'var(--color-basic-control-transparent-400)',
  select_outline_control_hover_border_color: 'var(--color-control-transparent-hover-border)',
  select_outline_control_disabled_background_color: 'var(--color-control-transparent-disabled)',
  select_outline_control_disabled_border_color: 'var(--color-basic-control-transparent-500)',
  select_outline_control_disabled_icon_color: 'var(--color-basic-100)',
  select_outline_control_disabled_text_color: 'var(--color-basic-100)',

  select_outline_adjacent_border_style: 'var(--select-outline-border-style)',
  select_outline_adjacent_border_width: 'var(--select-outline-border-width)',
  select_outline_basic_open_border_color: 'var(--select-outline-basic-border-color)',
  select_outline_basic_adjacent_border_color: 'var(--select-outline-basic-border-color)',
  select_outline_primary_open_border_color: 'var(--select-outline-primary-border-color)',
  select_outline_primary_adjacent_border_color: 'var(--select-outline-primary-border-color)',
  select_outline_success_open_border_color: 'var(--select-outline-success-border-color)',
  select_outline_success_adjacent_border_color: 'var(--select-outline-success-border-color)',
  select_outline_info_open_border_color: 'var(--select-outline-info-border-color)',
  select_outline_info_adjacent_border_color: 'var(--select-outline-info-border-color)',
  select_outline_warning_open_border_color: 'var(--select-outline-warning-border-color)',
  select_outline_warning_adjacent_border_color: 'var(--select-outline-warning-border-color)',
  select_outline_danger_open_border_color: 'var(--select-outline-danger-border-color)',
  select_outline_danger_adjacent_border_color: 'var(--select-outline-danger-border-color)',
  select_outline_control_open_border_color: 'var(--select-outline-control-border-color)',
  select_outline_control_adjacent_border_color: 'var(--select-outline-control-border-color)',

  select_filled_border_style: 'solid',
  select_filled_border_width: '1px',

  select_filled_tiny_padding: '0.1875rem 1rem',
  select_filled_small_padding: '0.1875rem 1rem',
  select_filled_medium_padding: '0.4375rem 1rem',
  select_filled_large_padding: '0.6875rem 1rem',
  select_filled_giant_padding: '0.9375rem 1rem',

  select_filled_basic_background_color: 'var(--color-basic-default)',
  select_filled_basic_border_color: 'var(--color-basic-default-border)',
  select_filled_basic_icon_color: 'var(--color-basic-800)',
  select_filled_basic_text_color: 'var(--color-basic-800)',
  select_filled_basic_placeholder_text_color: 'var(--text-hint-color)',

  select_filled_basic_focus_background_color: 'var(--color-basic-focus)',
  select_filled_basic_focus_border_color: 'var(--color-basic-focus-border)',
  select_filled_basic_hover_background_color: 'var(--color-basic-hover)',
  select_filled_basic_hover_border_color: 'var(--color-basic-hover-border)',
  select_filled_basic_disabled_background_color: 'var(--background-basic-color-2)',
  select_filled_basic_disabled_border_color: 'var(--border-basic-color-2)',
  select_filled_basic_disabled_icon_color: 'var(--text-disabled-color)',
  select_filled_basic_disabled_text_color: 'var(--text-disabled-color)',

  select_filled_primary_background_color: 'var(--color-primary-default)',
  select_filled_primary_border_color: 'var(--color-primary-default-border)',
  select_filled_primary_icon_color: 'var(--text-control-color)',
  select_filled_primary_text_color: 'var(--text-control-color)',
  select_filled_primary_placeholder_text_color: 'var(--text-control-color)',

  select_filled_primary_focus_background_color: 'var(--color-primary-focus)',
  select_filled_primary_focus_border_color: 'var(--color-primary-focus-border)',
  select_filled_primary_hover_background_color: 'var(--color-primary-hover)',
  select_filled_primary_hover_border_color: 'var(--color-primary-hover-border)',
  select_filled_primary_disabled_background_color: 'var(--background-basic-color-2)',
  select_filled_primary_disabled_border_color: 'var(--border-basic-color-2)',
  select_filled_primary_disabled_icon_color: 'var(--text-disabled-color)',
  select_filled_primary_disabled_text_color: 'var(--text-disabled-color)',

  select_filled_success_background_color: 'var(--color-success-default)',
  select_filled_success_border_color: 'var(--color-success-default-border)',
  select_filled_success_icon_color: 'var(--text-control-color)',
  select_filled_success_text_color: 'var(--text-control-color)',
  select_filled_success_placeholder_text_color: 'var(--text-control-color)',

  select_filled_success_focus_background_color: 'var(--color-success-focus)',
  select_filled_success_focus_border_color: 'var(--color-success-focus-border)',
  select_filled_success_hover_background_color: 'var(--color-success-hover)',
  select_filled_success_hover_border_color: 'var(--color-success-hover-border)',
  select_filled_success_disabled_background_color: 'var(--background-basic-color-2)',
  select_filled_success_disabled_border_color: 'var(--border-basic-color-2)',
  select_filled_success_disabled_icon_color: 'var(--text-disabled-color)',
  select_filled_success_disabled_text_color: 'var(--text-disabled-color)',

  select_filled_info_background_color: 'var(--color-info-default)',
  select_filled_info_border_color: 'var(--color-info-default-border)',
  select_filled_info_icon_color: 'var(--text-control-color)',
  select_filled_info_text_color: 'var(--text-control-color)',
  select_filled_info_placeholder_text_color: 'var(--text-control-color)',

  select_filled_info_focus_background_color: 'var(--color-info-focus)',
  select_filled_info_focus_border_color: 'var(--color-info-focus-border)',
  select_filled_info_hover_background_color: 'var(--color-info-hover)',
  select_filled_info_hover_border_color: 'var(--color-info-hover-border)',
  select_filled_info_disabled_background_color: 'var(--background-basic-color-2)',
  select_filled_info_disabled_border_color: 'var(--border-basic-color-2)',
  select_filled_info_disabled_icon_color: 'var(--text-disabled-color)',
  select_filled_info_disabled_text_color: 'var(--text-disabled-color)',

  select_filled_warning_background_color: 'var(--color-warning-default)',
  select_filled_warning_border_color: 'var(--color-warning-default-border)',
  select_filled_warning_icon_color: 'var(--text-control-color)',
  select_filled_warning_text_color: 'var(--text-control-color)',
  select_filled_warning_placeholder_text_color: 'var(--text-control-color)',

  select_filled_warning_focus_background_color: 'var(--color-warning-focus)',
  select_filled_warning_focus_border_color: 'var(--color-warning-focus-border)',
  select_filled_warning_hover_background_color: 'var(--color-warning-hover)',
  select_filled_warning_hover_border_color: 'var(--color-warning-hover-border)',
  select_filled_warning_disabled_background_color: 'var(--background-basic-color-2)',
  select_filled_warning_disabled_border_color: 'var(--border-basic-color-2)',
  select_filled_warning_disabled_icon_color: 'var(--text-disabled-color)',
  select_filled_warning_disabled_text_color: 'var(--text-disabled-color)',

  select_filled_danger_background_color: 'var(--color-danger-default)',
  select_filled_danger_border_color: 'var(--color-danger-default-border)',
  select_filled_danger_icon_color: 'var(--text-control-color)',
  select_filled_danger_text_color: 'var(--text-control-color)',
  select_filled_danger_placeholder_text_color: 'var(--text-control-color)',

  select_filled_danger_focus_background_color: 'var(--color-danger-focus)',
  select_filled_danger_focus_border_color: 'var(--color-danger-focus-border)',
  select_filled_danger_hover_background_color: 'var(--color-danger-hover)',
  select_filled_danger_hover_border_color: 'var(--color-danger-hover-border)',
  select_filled_danger_disabled_background_color: 'var(--background-basic-color-2)',
  select_filled_danger_disabled_border_color: 'var(--border-basic-color-2)',
  select_filled_danger_disabled_icon_color: 'var(--text-disabled-color)',
  select_filled_danger_disabled_text_color: 'var(--text-disabled-color)',

  select_filled_control_background_color: 'var(--color-control-default)',
  select_filled_control_border_color: 'var(--color-control-default-border)',
  select_filled_control_icon_color: 'var(--color-basic-800)',
  select_filled_control_text_color: 'var(--color-basic-800)',
  select_filled_control_placeholder_text_color: 'var(--text-hint-color)',

  select_filled_control_focus_background_color: 'var(--color-control-focus)',
  select_filled_control_focus_border_color: 'var(--color-control-focus-border)',
  select_filled_control_hover_background_color: 'var(--color-control-hover)',
  select_filled_control_hover_border_color: 'var(--color-control-hover-border)',
  select_filled_control_disabled_background_color: 'var(--background-basic-color-2)',
  select_filled_control_disabled_border_color: 'var(--border-basic-color-2)',
  select_filled_control_disabled_icon_color: 'var(--text-disabled-color)',
  select_filled_control_disabled_text_color: 'var(--text-disabled-color)',

  select_hero_tiny_padding: '0.25rem 1rem',
  select_hero_small_padding: '0.25rem 1rem',
  select_hero_medium_padding: '0.5rem 1rem',
  select_hero_large_padding: '0.75rem 1rem',
  select_hero_giant_padding: '1rem 1rem',

  select_hero_basic_left_background_color: 'var(--color-basic-200)',
  select_hero_basic_right_background_color: 'var(--color-basic-default)',
  select_hero_basic_icon_color: 'var(--color-basic-800)',
  select_hero_basic_text_color: 'var(--color-basic-800)',
  select_hero_basic_placeholder_text_color: 'var(--text-hint-color)',

  select_hero_basic_focus_left_background_color: 'var(--color-basic-300)',
  select_hero_basic_focus_right_background_color: 'var(--color-basic-400)',
  select_hero_basic_hover_left_background_color: 'var(--color-basic-100)',
  select_hero_basic_hover_right_background_color: 'var(--color-basic-hover)',
  select_hero_basic_disabled_background_color: 'var(--background-basic-color-2)',
  select_hero_basic_disabled_icon_color: 'var(--text-disabled-color)',
  select_hero_basic_disabled_text_color: 'var(--text-disabled-color)',

  select_hero_primary_left_background_color: 'var(--color-primary-400)',
  select_hero_primary_right_background_color: 'var(--color-primary-default)',
  select_hero_primary_icon_color: 'var(--text-control-color)',
  select_hero_primary_text_color: 'var(--text-control-color)',
  select_hero_primary_placeholder_text_color: 'var(--text-control-color)',

  select_hero_primary_focus_left_background_color: 'var(--color-primary-500)',
  select_hero_primary_focus_right_background_color: 'var(--color-primary-focus)',
  select_hero_primary_hover_left_background_color: 'var(--color-primary-300)',
  select_hero_primary_hover_right_background_color: 'var(--color-primary-hover)',
  select_hero_primary_disabled_background_color: 'var(--background-basic-color-2)',
  select_hero_primary_disabled_icon_color: 'var(--text-disabled-color)',
  select_hero_primary_disabled_text_color: 'var(--text-disabled-color)',

  select_hero_success_left_background_color: 'var(--color-success-400)',
  select_hero_success_right_background_color: 'var(--color-success-default)',
  select_hero_success_icon_color: 'var(--text-control-color)',
  select_hero_success_text_color: 'var(--text-control-color)',
  select_hero_success_placeholder_text_color: 'var(--text-control-color)',

  select_hero_success_focus_left_background_color: 'var(--color-success-500)',
  select_hero_success_focus_right_background_color: 'var(--color-success-focus)',
  select_hero_success_hover_left_background_color: 'var(--color-success-300)',
  select_hero_success_hover_right_background_color: 'var(--color-success-hover)',
  select_hero_success_disabled_background_color: 'var(--background-basic-color-2)',
  select_hero_success_disabled_icon_color: 'var(--text-disabled-color)',
  select_hero_success_disabled_text_color: 'var(--text-disabled-color)',

  select_hero_info_left_background_color: 'var(--color-info-400)',
  select_hero_info_right_background_color: 'var(--color-info-default)',
  select_hero_info_icon_color: 'var(--text-control-color)',
  select_hero_info_text_color: 'var(--text-control-color)',
  select_hero_info_placeholder_text_color: 'var(--text-control-color)',

  select_hero_info_focus_left_background_color: 'var(--color-info-500)',
  select_hero_info_focus_right_background_color: 'var(--color-info-focus)',
  select_hero_info_hover_left_background_color: 'var(--color-info-300)',
  select_hero_info_hover_right_background_color: 'var(--color-info-hover)',
  select_hero_info_disabled_background_color: 'var(--background-basic-color-2)',
  select_hero_info_disabled_icon_color: 'var(--text-disabled-color)',
  select_hero_info_disabled_text_color: 'var(--text-disabled-color)',

  select_hero_warning_left_background_color: 'var(--color-warning-400)',
  select_hero_warning_right_background_color: 'var(--color-warning-default)',
  select_hero_warning_icon_color: 'var(--text-control-color)',
  select_hero_warning_text_color: 'var(--text-control-color)',
  select_hero_warning_placeholder_text_color: 'var(--text-control-color)',

  select_hero_warning_focus_left_background_color: 'var(--color-warning-500)',
  select_hero_warning_focus_right_background_color: 'var(--color-warning-focus)',
  select_hero_warning_hover_left_background_color: 'var(--color-warning-300)',
  select_hero_warning_hover_right_background_color: 'var(--color-warning-hover)',
  select_hero_warning_disabled_background_color: 'var(--background-basic-color-2)',
  select_hero_warning_disabled_icon_color: 'var(--text-disabled-color)',
  select_hero_warning_disabled_text_color: 'var(--text-disabled-color)',

  select_hero_danger_left_background_color: 'var(--color-danger-400)',
  select_hero_danger_right_background_color: 'var(--color-danger-default)',
  select_hero_danger_icon_color: 'var(--text-control-color)',
  select_hero_danger_text_color: 'var(--text-control-color)',
  select_hero_danger_placeholder_text_color: 'var(--text-control-color)',

  select_hero_danger_focus_left_background_color: 'var(--color-danger-500)',
  select_hero_danger_focus_right_background_color: 'var(--color-danger-focus)',
  select_hero_danger_hover_left_background_color: 'var(--color-danger-300)',
  select_hero_danger_hover_right_background_color: 'var(--color-danger-hover)',
  select_hero_danger_disabled_background_color: 'var(--background-basic-color-2)',
  select_hero_danger_disabled_icon_color: 'var(--text-disabled-color)',
  select_hero_danger_disabled_text_color: 'var(--text-disabled-color)',

  select_hero_control_left_background_color: 'var(--color-control-default)',
  select_hero_control_right_background_color: 'var(--color-control-default)',
  select_hero_control_icon_color: 'var(--color-basic-800)',
  select_hero_control_text_color: 'var(--color-basic-800)',
  select_hero_control_placeholder_text_color: 'var(--text-hint-color)',

  select_hero_control_focus_left_background_color: 'var(--color-basic-200)',
  select_hero_control_focus_right_background_color: 'var(--color-control-focus)',
  select_hero_control_hover_left_background_color: 'var(--color-basic-100)',
  select_hero_control_hover_right_background_color: 'var(--color-control-hover)',
  select_hero_control_disabled_background_color: 'var(--background-basic-color-2)',
  select_hero_control_disabled_icon_color: 'var(--text-disabled-color)',
  select_hero_control_disabled_text_color: 'var(--text-disabled-color)'
};
