import { NebularThemeCalendar } from '../types/nebular-theme';

const calendar_text_font_size = 'var(--text_subtitle_font_size)';
const calendar_text_font_weight = 'var(--text_subtitle_font_weight)';
const calendar_text_line_height = 'var(--text_subtitle_line_height)';
const calendar_weekday_text_color = 'var(--text_hint_color)';

export const DefaultThemeCalendar: NebularThemeCalendar = {
  calendar_width: '20.625rem',
  calendar_background_color: 'var(--background-basic-color-1)',
  calendar_border_color: 'var(--border-basic-color-4)',
  calendar_border_style: 'solid',
  calendar_border_width: '0.0625rem',
  calendar_border_radius: 'var(--border-radius)',
  calendar_text_color: 'var(--text-basic-color)',
  calendar_text_font_family: 'var(--text-subtitle-font-family)',
  calendar_text_font_size,
  calendar_text_font_weight,
  calendar_text_line_height,

  calendar_picker_padding_top: '0.25rem',
  calendar_picker_padding_bottom: '0.625rem',
  calendar_picker_padding_start: '0.625rem',
  calendar_picker_padding_end: '0.625rem',

  calendar_navigation_text_color: 'var(--text-basic-color)',
  calendar_navigation_text_font_family: 'var(--text-button-font-family)',
  calendar_navigation_title_text_font_size: 'var(--text-button-medium-font-size)',
  calendar_navigation_title_text_font_weight: 'var(--text-button-font-weight)',
  calendar_navigation_title_text_line_height: 'var(--text-button-medium-line-height)',
  calendar_navigation_padding: '0.625rem 0.25rem',

  calendar_cell_inactive_text_color: 'var(--text-hint-color)',

  calendar_cell_disabled_text_color: 'var(--text-disabled-color)',

  calendar_cell_hover_background_color: 'var(--background-basic-color-2)',
  calendar_cell_hover_border_color: 'var(--background-basic-color-2)',
  calendar_cell_hover_text_color: 'var(--text-basic-color)',
  calendar_cell_hover_text_font_size: 'var(--calendar-text-font-size)',
  calendar_cell_hover_text_font_weight: 'var(--calendar-text-font-weight)',
  calendar_cell_hover_text_line_height: 'var(--calendar-text-line-height)',

  calendar_cell_active_background_color: 'var(--color-primary-active)',
  calendar_cell_active_border_color: 'var(--color-primary-active-border)',
  calendar_cell_active_text_color: 'var(--text-control-color)',
  calendar_cell_active_text_font_size: 'var(--calendar-text-font-size)',
  calendar_cell_active_text_font_weight: 'var(--calendar-text-font-weight)',
  calendar_cell_active_text_line_height: 'var(--calendar-text-line-height)',

  calendar_cell_today_background_color: 'var(--color-primary-transparent-default)',
  calendar_cell_today_border_color: 'var(--color-primary-transparent-default-border)',
  calendar_cell_today_text_color: 'var(--text-basic-color)',
  calendar_cell_today_text_font_size: 'var(--calendar-text-font-size)',
  calendar_cell_today_text_font_weight: 'var(--calendar-text-font-weight)',
  calendar_cell_today_text_line_height: 'var(--calendar-text-line-height)',
  calendar_cell_today_hover_background_color: 'var(--color-primary-transparent-hover)',
  calendar_cell_today_hover_border_color: 'var(--color-primary-transparent-hover-border)',
  calendar_cell_today_active_background_color: 'var(--color-primary-transparent-active)',
  calendar_cell_today_active_border_color: 'var(--color-primary-transparent-active-border)',
  calendar_cell_today_disabled_border_color: 'var(--border-basic-color-4)',

  calendar_cell_today_selected_background_color: 'var(--color-control-transparent-default)',
  calendar_cell_today_selected_border_color: 'transparent',
  calendar_cell_today_selected_text_color: 'var(--text-control-color)',
  calendar_cell_today_selected_hover_background_color: 'var(--color-control-transparent-hover)',
  calendar_cell_today_selected_hover_border_color: 'transparent',
  calendar_cell_today_selected_active_background_color: 'var(--color-control-transparent-active)',
  calendar_cell_today_selected_active_border_color: 'transparent',

  calendar_cell_today_in_range_background_color: 'var(--color-control-transparent-default)',
  calendar_cell_today_in_range_border_color: 'transparent',
  calendar_cell_today_in_range_text_color: 'var(--text-control-color)',
  calendar_cell_today_in_range_hover_background_color: 'var(--color-control-transparent-hover)',
  calendar_cell_today_in_range_hover_border_color: 'transparent',
  calendar_cell_today_in_range_active_background_color: 'var(--color-control-transparent-active)',
  calendar_cell_today_in_range_active_border_color: 'transparent',

  calendar_cell_selected_background_color: 'var(--color-primary-default)',
  calendar_cell_selected_border_color: 'var(--color-primary-default-border)',
  calendar_cell_selected_text_color: 'var(--text-control-color)',
  calendar_cell_selected_text_font_size: 'var(--calendar-text-font-size)',
  calendar_cell_selected_text_font_weight: 'var(--calendar-text-font-weight)',
  calendar_cell_selected_text_line_height: 'var(--calendar-text-line-height)',
  calendar_cell_selected_hover_background_color: 'var(--color-primary-hover)',
  calendar_cell_selected_hover_border_color: 'var(--color-primary-hover-border)',
  calendar_cell_selected_active_background_color: 'var(--color-primary-active)',
  calendar_cell_selected_active_border_color: 'var(--color-primary-active-border)',

  calendar_day_cell_width: '2.75rem',
  calendar_day_cell_height: '2.75rem',
  calendar_month_cell_width: '4.8125rem',
  calendar_month_cell_height: 'var(--calendar-day-cell-height)',
  calendar_year_cell_width: 'var(--calendar-month-cell-width)',
  calendar_year_cell_height: 'var(--calendar-month-cell-height)',

  calendar_weekday_background: 'transparent',
  calendar_weekday_divider_color: 'var(--divider-color)',
  calendar_weekday_divider_width: 'var(--divider-width)',
  calendar_weekday_text_color,
  calendar_weekday_text_font_size: 'var(--text-subtitle-font-size)',
  calendar_weekday_text_font_weight: 'var(--text-subtitle-font-weight)',
  calendar_weekday_text_line_height: 'var(--text-subtitle-line-height)',
  calendar_weekday_holiday_text_color: 'var(--calendar-weekday-text-color)',
  calendar_weekday_height: 'var(--calendar-day-cell-height)',
  calendar_weekday_width: 'var(--calendar-day-cell-width)',

  calendar_weeknumber_background: 'transparent',
  calendar_weeknumber_divider_color: 'var(--divider-color)',
  calendar_weeknumber_divider_width: 'var(--divider-width)',
  calendar_weeknumber_text_color: 'var(--text-hint-color)',
  calendar_weeknumber_text_font_size: 'var(--text-subtitle-font-size)',
  calendar_weeknumber_text_font_weight: 'var(--text-subtitle-font-weight)',
  calendar_weeknumber_text_line_height: 'var(--text-subtitle-line-height)',
  calendar_weeknumber_height: 'var(--calendar-weekday-height)',
  calendar_weeknumber_width: 'var(--calendar-weekday-width)',

  calendar_large_width: '22.375rem',
  calendar_day_cell_large_width: '3rem',
  calendar_day_cell_large_height: '3rem',
  calendar_weekday_large_height: 'var(--calendar-day-cell-large-width)',
  calendar_weekday_large_width: 'var(--calendar-day-cell-large-height)',
  calendar_weeknumber_large_height: 'var(--calendar-weekday-large-height)',
  calendar_weeknumber_large_width: 'var(--calendar-weekday-large-width)',
  calendar_month_cell_large_width: '5.25rem',
  calendar_month_cell_large_height: 'var(--calendar-day-cell-large-height)',
  calendar_year_cell_large_width: 'var(--calendar-month-cell-large-width)',
  calendar_year_cell_large_height: 'var(--calendar-month-cell-large-height)'
};
