import { NebularThemeUser } from '../types/nebular-theme';

export const DefaultThemeUser: NebularThemeUser = {
  user_picture_box_background_color: 'transparent',
  user_picture_box_border_color: 'var(--border-basic-color-3)',
  user_picture_box_border_width: '1px',
  user_initials_text_color: 'var(--text-basic-color)',
  user_initials_text_font_family: 'var(--text-paragraph-font-family)',
  user_initials_text_font_weight: 'var(--text-paragraph-font-weight)',
  user_name_text_color: 'var(--text-basic-color)',
  user_name_text_font_family: 'var(--text-paragraph-font-family)',
  user_name_text_font_weight: 'var(--text-paragraph-font-weight)',
  user_title_text_color: 'var(--text-basic-color)',
  user_title_text_font_family: 'var(--text-paragraph-2-font-family)',
  user_title_text_font_weight: 'var(--text-paragraph-2-font-weight)',

  user_rectangle_border_radius: '0.5rem',
  user_semiround_border_radius: '0.75rem',
  user_round_border_radius: '50%',

  user_tiny_height: '1.25rem',
  user_tiny_width: '1.25rem',
  user_tiny_initials_text_font_size: 'var(--text-caption-font-size)',
  user_tiny_initials_text_line_height: 'var(--text-caption-line-height)',
  user_tiny_name_text_font_size: 'var(--text-caption-font-size)',
  user_tiny_name_text_line_height: 'var(--text-caption-line-height)',
  user_tiny_title_text_font_size: 'var(--text-caption-font-size)',
  user_tiny_title_text_line_height: 'var(--text-caption-line-height)',

  user_small_height: '1.5rem',
  user_small_width: '1.5rem',
  user_small_initials_text_font_size: 'var(--text-caption-font-size)',
  user_small_initials_text_line_height: 'var(--text-caption-line-height)',
  user_small_name_text_font_size: 'var(--text-caption-font-size)',
  user_small_name_text_line_height: 'var(--text-caption-line-height)',
  user_small_title_text_font_size: 'var(--text-caption-font-size)',
  user_small_title_text_line_height: 'var(--text-caption-line-height)',

  user_medium_height: '2.5rem',
  user_medium_width: '2.5rem',
  user_medium_initials_text_font_size: 'var(--text-paragraph-font-size)',
  user_medium_initials_text_line_height: 'var(--text-paragraph-line-height)',
  user_medium_name_text_font_size: 'var(--text-paragraph-font-size)',
  user_medium_name_text_line_height: 'var(--text-paragraph-line-height)',
  user_medium_title_text_font_size: 'var(--text-caption-font-size)',
  user_medium_title_text_line_height: 'var(--text-caption-line-height)',

  user_large_height: '3.25rem',
  user_large_width: '3.25rem',
  user_large_initials_text_font_size: 'var(--text-paragraph-font-size)',
  user_large_initials_text_line_height: 'var(--text-paragraph-line-height)',
  user_large_name_text_font_size: 'var(--text-paragraph-font-size)',
  user_large_name_text_line_height: 'var(--text-paragraph-line-height)',
  user_large_title_text_font_size: 'var(--text-paragraph-2-font-size)',
  user_large_title_text_line_height: 'var(--text-paragraph-2-line-height)',

  user_giant_height: '4rem',
  user_giant_width: '4rem',
  user_giant_initials_text_font_size: 'var(--text-paragraph-font-size)',
  user_giant_initials_text_line_height: 'var(--text-paragraph-line-height)',
  user_giant_name_text_font_size: 'var(--text-paragraph-font-size)',
  user_giant_name_text_line_height: 'var(--text-paragraph-line-height)',
  user_giant_title_text_font_size: 'var(--text-paragraph-font-size)',
  user_giant_title_text_line_height: 'var(--text-paragraph-line-height)'
};
