import { NebularThemeAlert } from '../types/nebular-theme';

export const DefaultThemeAlert: NebularThemeAlert = {
  alert_border_radius: 'var(--border-radius)',
  alert_bottom_margin: '1.5rem',
  alert_padding: '1rem 1.125rem',
  alert_scrollbar_color: 'var(--scrollbar-color)',
  alert_scrollbar_background_color: 'var(--scrollbar-background-color)',
  alert_scrollbar_width: 'var(--scrollbar-width)',
  alert_shadow: 'none',
  alert_text_font_family: 'var(--text-paragraph-font-family)',
  alert_text_font_size: 'var(--text-subtitle-font-size)',
  alert_text_font_weight: 'var(--text-subtitle-font-weight)',
  alert_text_line_height: 'var(--text-subtitle-line-height)',

  alert_closable_start_padding: '3rem',
  alert_close_font_weight: 700,
  alert_close_text_shadow: '0 1px 0 #fff',
  alert_close_opacity: '0.5',
  alert_close_hover_focus_opacity: '0.75',

  alert_tiny_height: '4.5rem',
  alert_small_height: '5.75rem',
  alert_medium_height: '7rem',
  alert_medium_padding: '1rem 1.125rem',
  alert_large_height: '8.25rem',
  alert_giant_height: '9.5rem',

  alert_basic_background_color: 'var(--background-basic-color-2)',
  alert_basic_text_color: 'var(--text-basic-color)',
  alert_primary_background_color: 'var(--color-primary-default)',
  alert_primary_text_color: 'var(--text-control-color)',
  alert_success_background_color: 'var(--color-success-default)',
  alert_success_text_color: 'var(--text-control-color)',
  alert_info_background_color: 'var(--color-info-default)',
  alert_info_text_color: 'var(--text-control-color)',
  alert_warning_background_color: 'var(--color-warning-default)',
  alert_warning_text_color: 'var(--text-control-color)',
  alert_danger_background_color: 'var(--color-danger-default)',
  alert_danger_text_color: 'var(--text-control-color)',
  alert_control_background_color: 'var(--color-control-default)',
  alert_control_text_color: 'var(--color-basic-800)',

  alert_accent_basic_color: 'var(--border-basic-color-3)',
  alert_accent_primary_color: 'var(--color-primary-default)',
  alert_accent_info_color: 'var(--color-info-default)',
  alert_accent_success_color: 'var(--color-success-default)',
  alert_accent_warning_color: 'var(--color-warning-default)',
  alert_accent_danger_color: 'var(--color-danger-default)',
  alert_accent_control_color: 'var(--color-control-default)',

  alert_outline_width: '1px',
  alert_outline_basic_color: 'var(--color-basic-focus-border)',
  alert_outline_primary_color: 'var(--color-primary-focus-border)',
  alert_outline_info_color: 'var(--color-info-focus-border)',
  alert_outline_success_color: 'var(--color-success-focus-border)',
  alert_outline_warning_color: 'var(--color-warning-focus-border)',
  alert_outline_danger_color: 'var(--color-danger-focus-border)',
  alert_outline_control_color: 'var(--color-control-focus-border)'
};
