import { NebularThemeTag } from '../types/nebular-theme';

export const DefaultThemeTag: NebularThemeTag = {
  tag_text_font_family: 'var(--text-subtitle-font-family)',
  tag_text_transform: 'capitalize',
  tag_border_width: '0.0625rem',
  tag_border_style: 'solid',
  tag_border_radius: '1.5rem',

  tag_tiny_text_font_size: 'var(--input-tiny-text-font-size)',
  tag_tiny_text_font_weight: 'var(--input-tiny-text-font-weight)',
  tag_tiny_text_line_height: 'var(--input-tiny-text-line-height)',
  tag_tiny_padding: '0.0625rem 0.9375rem',
  tag_tiny_close_offset: '0.625rem',

  tag_small_text_font_size: 'var(--input-small-text-font-size)',
  tag_small_text_font_weight: 'var(--input-small-text-font-weight)',
  tag_small_text_line_height: 'var(--input-small-text-line-height)',
  tag_small_padding: '0.0625rem 0.9375rem',
  tag_small_close_offset: '0.625rem',

  tag_medium_text_font_size: 'var(--input-medium-text-font-size)',
  tag_medium_text_font_weight: 'var(--input-medium-text-font-weight)',
  tag_medium_text_line_height: 'var(--input-medium-text-line-height)',
  tag_medium_padding: '0.1875rem 0.9375rem',
  tag_medium_close_offset: '0.625rem',

  tag_large_text_font_size: 'var(--input-large-text-font-size)',
  tag_large_text_font_weight: 'var(--input-large-text-font-weight)',
  tag_large_text_line_height: 'var(--input-large-text-line-height)',
  tag_large_padding: '0.3125rem 0.9375rem',
  tag_large_close_offset: '0.625rem',

  tag_giant_text_font_size: 'var(--input-giant-text-font-size)',
  tag_giant_text_font_weight: 'var(--input-giant-text-font-weight)',
  tag_giant_text_line_height: 'var(--input-giant-text-line-height)',
  tag_giant_padding: '0.4375rem 0.9375rem',
  tag_giant_close_offset: '0.625rem',

  tag_filled_basic_background_color: 'var(--color-basic-default)',
  tag_filled_basic_border_color: 'var(--color-basic-default-border)',
  tag_filled_basic_text_color: 'var(--color-basic-800)',
  tag_filled_basic_active_background_color: 'var(--color-basic-focus)',
  tag_filled_basic_active_border_color: 'var(--color-basic-focus-border)',
  tag_filled_basic_hover_background_color: 'var(--color-basic-hover)',
  tag_filled_basic_hover_border_color: 'var(--color-basic-hover-border)',
  tag_filled_basic_selected_background_color: 'var(--color-basic-active)',
  tag_filled_basic_selected_border_color: 'var(--color-basic-active-border)',

  tag_filled_primary_background_color: 'var(--color-primary-default)',
  tag_filled_primary_border_color: 'var(--color-primary-default-border)',
  tag_filled_primary_text_color: 'var(--text-control-color)',
  tag_filled_primary_active_background_color: 'var(--color-primary-focus)',
  tag_filled_primary_active_border_color: 'var(--color-primary-focus-border)',
  tag_filled_primary_hover_background_color: 'var(--color-primary-hover)',
  tag_filled_primary_hover_border_color: 'var(--color-primary-hover-border)',
  tag_filled_primary_selected_background_color: 'var(--color-primary-active)',
  tag_filled_primary_selected_border_color: 'var(--color-primary-active-border)',

  tag_filled_success_background_color: 'var(--color-success-default)',
  tag_filled_success_border_color: 'var(--color-success-default-border)',
  tag_filled_success_text_color: 'var(--text-control-color)',
  tag_filled_success_active_background_color: 'var(--color-success-focus)',
  tag_filled_success_active_border_color: 'var(--color-success-focus-border)',
  tag_filled_success_hover_background_color: 'var(--color-success-hover)',
  tag_filled_success_hover_border_color: 'var(--color-success-hover-border)',
  tag_filled_success_selected_background_color: 'var(--color-success-active)',
  tag_filled_success_selected_border_color: 'var(--color-success-active-border)',

  tag_filled_info_background_color: 'var(--color-info-default)',
  tag_filled_info_border_color: 'var(--color-info-default-border)',
  tag_filled_info_text_color: 'var(--text-control-color)',
  tag_filled_info_active_background_color: 'var(--color-info-focus)',
  tag_filled_info_active_border_color: 'var(--color-info-focus-border)',
  tag_filled_info_hover_background_color: 'var(--color-info-hover)',
  tag_filled_info_hover_border_color: 'var(--color-info-hover-border)',
  tag_filled_info_selected_background_color: 'var(--color-info-active)',
  tag_filled_info_selected_border_color: 'var(--color-info-active-border)',

  tag_filled_warning_background_color: 'var(--color-warning-default)',
  tag_filled_warning_border_color: 'var(--color-warning-default-border)',
  tag_filled_warning_text_color: 'var(--text-control-color)',
  tag_filled_warning_active_background_color: 'var(--color-warning-focus)',
  tag_filled_warning_active_border_color: 'var(--color-warning-focus-border)',
  tag_filled_warning_hover_background_color: 'var(--color-warning-hover)',
  tag_filled_warning_hover_border_color: 'var(--color-warning-hover-border)',
  tag_filled_warning_selected_background_color: 'var(--color-warning-active)',
  tag_filled_warning_selected_border_color: 'var(--color-warning-active-border)',

  tag_filled_danger_background_color: 'var(--color-danger-default)',
  tag_filled_danger_border_color: 'var(--color-danger-default-border)',
  tag_filled_danger_text_color: 'var(--text-control-color)',
  tag_filled_danger_active_background_color: 'var(--color-danger-focus)',
  tag_filled_danger_active_border_color: 'var(--color-danger-focus-border)',
  tag_filled_danger_hover_background_color: 'var(--color-danger-hover)',
  tag_filled_danger_hover_border_color: 'var(--color-danger-hover-border)',
  tag_filled_danger_selected_background_color: 'var(--color-danger-active)',
  tag_filled_danger_selected_border_color: 'var(--color-danger-active-border)',

  tag_filled_control_background_color: 'var(--color-control-default)',
  tag_filled_control_border_color: 'var(--color-control-default-border)',
  tag_filled_control_text_color: 'var(--color-basic-800)',
  tag_filled_control_active_background_color: 'var(--color-control-hover)',
  tag_filled_control_active_border_color: 'var(--color-control-hover-border)',
  tag_filled_control_hover_background_color: 'var(--color-control-focus)',
  tag_filled_control_hover_border_color: 'var(--color-control-focus-border)',
  tag_filled_control_selected_background_color: 'var(--color-control-active)',
  tag_filled_control_selected_border_color: 'var(--color-control-active-border)',

  tag_outline_basic_background_color: 'var(--color-basic-transparent-default)',
  tag_outline_basic_border_color: 'var(--color-basic-transparent-default-border)',
  tag_outline_basic_text_color: 'var(--text-hint-color)',
  tag_outline_basic_active_background_color: 'var(--color-basic-transparent-focus)',
  tag_outline_basic_active_border_color: 'var(--color-basic-transparent-focus-border)',
  tag_outline_basic_active_text_color: 'var(--text-hint-color)',
  tag_outline_basic_hover_background_color: 'var(--color-basic-transparent-hover)',
  tag_outline_basic_hover_border_color: 'var(--color-basic-transparent-hover-border)',
  tag_outline_basic_hover_text_color: 'var(--text-hint-color)',
  tag_outline_basic_selected_background_color: 'var(--color-basic-transparent-active)',
  tag_outline_basic_selected_border_color: 'var(--color-basic-transparent-active-border)',
  tag_outline_basic_selected_text_color: 'var(--text-hint-color)',

  tag_outline_primary_background_color: 'var(--color-primary-transparent-default)',
  tag_outline_primary_border_color: 'var(--color-primary-transparent-default-border)',
  tag_outline_primary_text_color: 'var(--text-primary-color)',
  tag_outline_primary_active_background_color: 'var(--color-primary-transparent-focus)',
  tag_outline_primary_active_border_color: 'var(--color-primary-transparent-focus-border)',
  tag_outline_primary_active_text_color: 'var(--text-primary-color)',
  tag_outline_primary_hover_background_color: 'var(--color-primary-transparent-hover)',
  tag_outline_primary_hover_border_color: 'var(--color-primary-transparent-hover-border)',
  tag_outline_primary_hover_text_color: 'var(--text-primary-color)',
  tag_outline_primary_selected_background_color: 'var(--color-primary-transparent-active)',
  tag_outline_primary_selected_border_color: 'var(--color-primary-transparent-active-border)',
  tag_outline_primary_selected_text_color: 'var(--text-primary-color)',

  tag_outline_success_background_color: 'var(--color-success-transparent-default)',
  tag_outline_success_border_color: 'var(--color-success-transparent-default-border)',
  tag_outline_success_text_color: 'var(--text-success-color)',
  tag_outline_success_active_background_color: 'var(--color-success-transparent-focus)',
  tag_outline_success_active_border_color: 'var(--color-success-transparent-focus-border)',
  tag_outline_success_active_text_color: 'var(--text-success-color)',
  tag_outline_success_hover_background_color: 'var(--color-success-transparent-hover)',
  tag_outline_success_hover_border_color: 'var(--color-success-transparent-hover-border)',
  tag_outline_success_hover_text_color: 'var(--text-success-color)',
  tag_outline_success_selected_background_color: 'var(--color-success-transparent-active)',
  tag_outline_success_selected_border_color: 'var(--color-success-transparent-active-border)',
  tag_outline_success_selected_text_color: 'var(--text-success-color)',

  tag_outline_info_background_color: 'var(--color-info-transparent-default)',
  tag_outline_info_border_color: 'var(--color-info-transparent-default-border)',
  tag_outline_info_text_color: 'var(--text-info-color)',
  tag_outline_info_active_background_color: 'var(--color-info-transparent-focus)',
  tag_outline_info_active_border_color: 'var(--color-info-transparent-focus-border)',
  tag_outline_info_active_text_color: 'var(--text-info-color)',
  tag_outline_info_hover_background_color: 'var(--color-info-transparent-hover)',
  tag_outline_info_hover_border_color: 'var(--color-info-transparent-hover-border)',
  tag_outline_info_hover_text_color: 'var(--text-info-color)',
  tag_outline_info_selected_background_color: 'var(--color-info-transparent-active)',
  tag_outline_info_selected_border_color: 'var(--color-info-transparent-active-border)',
  tag_outline_info_selected_text_color: 'var(--text-info-color)',

  tag_outline_warning_background_color: 'var(--color-warning-transparent-default)',
  tag_outline_warning_border_color: 'var(--color-warning-transparent-default-border)',
  tag_outline_warning_text_color: 'var(--text-warning-color)',
  tag_outline_warning_active_background_color: 'var(--color-warning-transparent-focus)',
  tag_outline_warning_active_border_color: 'var(--color-warning-transparent-focus-border)',
  tag_outline_warning_active_text_color: 'var(--text-warning-color)',
  tag_outline_warning_hover_background_color: 'var(--color-warning-transparent-hover)',
  tag_outline_warning_hover_border_color: 'var(--color-warning-transparent-hover-border)',
  tag_outline_warning_hover_text_color: 'var(--text-warning-color)',
  tag_outline_warning_selected_background_color: 'var(--color-warning-transparent-active)',
  tag_outline_warning_selected_border_color: 'var(--color-warning-transparent-active-border)',
  tag_outline_warning_selected_text_color: 'var(--text-warning-color)',

  tag_outline_danger_background_color: 'var(--color-danger-transparent-default)',
  tag_outline_danger_border_color: 'var(--color-danger-transparent-default-border)',
  tag_outline_danger_text_color: 'var(--text-danger-color)',
  tag_outline_danger_active_background_color: 'var(--color-danger-transparent-focus)',
  tag_outline_danger_active_border_color: 'var(--color-danger-transparent-focus-border)',
  tag_outline_danger_active_text_color: 'var(--text-danger-color)',
  tag_outline_danger_hover_background_color: 'var(--color-danger-transparent-hover)',
  tag_outline_danger_hover_border_color: 'var(--color-danger-transparent-hover-border)',
  tag_outline_danger_hover_text_color: 'var(--text-danger-color)',
  tag_outline_danger_selected_background_color: 'var(--color-danger-transparent-active)',
  tag_outline_danger_selected_border_color: 'var(--color-danger-transparent-active-border)',
  tag_outline_danger_selected_text_color: 'var(--text-danger-color)',

  tag_outline_control_background_color: 'var(--color-control-transparent-default)',
  tag_outline_control_border_color: 'var(--color-control-transparent-default-border)',
  tag_outline_control_text_color: 'var(--text-control-color)',
  tag_outline_control_active_background_color: 'var(--color-control-transparent-focus)',
  tag_outline_control_active_border_color: 'var(--color-control-transparent-focus-border)',
  tag_outline_control_active_text_color: 'var(--text-control-color)',
  tag_outline_control_hover_background_color: 'var(--color-control-transparent-hover)',
  tag_outline_control_hover_border_color: 'var(--color-control-transparent-hover-border)',
  tag_outline_control_hover_text_color: 'var(--text-control-color)',
  tag_outline_control_selected_background_color: 'var(--color-control-transparent-active)',
  tag_outline_control_selected_border_color: 'var(--color-control-transparent-active-border)',
  tag_outline_control_selected_text_color: 'var(--text-control-color)',

  tag_list_tiny_tag_offset: '0.0625rem',
  tag_list_small_tag_offset: '0.125rem',
  tag_list_medium_tag_offset: '0.25rem',
  tag_list_large_tag_offset: '0.375rem',
  tag_list_giant_tag_offset: '0.5rem',

  tag_list_with_input_tiny_padding: '0.0625rem 1rem',
  tag_list_with_input_small_padding: '0.0625rem 1rem',
  tag_list_with_input_medium_padding: '0.1875rem 1rem',
  tag_list_with_input_large_padding: '0.3125rem 1rem',
  tag_list_with_input_giant_padding: '0.4375rem 1rem',

  tag_list_with_input_rectangle_border_radius: 'var(--input-rectangle-border-radius)',
  tag_list_with_input_semiround_border_radius: 'var(--input-semiround-border-radius)',
  tag_list_with_input_round_border_radius: 'var(--input-round-border-radius)',

  tag_input_min_width: '6rem',
  tag_input_text_font_family: 'var(--input-text-font-family)',
  tag_input_placeholder_text_font_family: 'var(--input-placeholder-text-font-family)',

  tag_input_basic_background_color: 'var(--input-basic-background-color)',
  tag_input_basic_border_color: 'var(--input-basic-border-color)',
  tag_input_basic_text_color: 'var(--input-basic-text-color)',
  tag_input_basic_placeholder_text_color: 'var(--input-basic-placeholder-text-color)',
  tag_input_basic_focus_background_color: 'var(--input-basic-focus-background-color)',
  tag_input_basic_focus_border_color: 'var(--input-basic-focus-border-color)',
  tag_input_basic_disabled_text_color: 'var(--input-basic-disabled-text-color)',
  tag_input_basic_disabled_placeholder_text_color:
    'var(--input-basic-disabled-placeholder-text-color)',

  tag_input_primary_background_color: 'var(--input-primary-background-color)',
  tag_input_primary_border_color: 'var(--input-primary-border-color)',
  tag_input_primary_text_color: 'var(--input-primary-text-color)',
  tag_input_primary_placeholder_text_color: 'var(--input-primary-placeholder-text-color)',
  tag_input_primary_focus_background_color: 'var(--input-primary-focus-background-color)',
  tag_input_primary_focus_border_color: 'var(--input-primary-focus-border-color)',
  tag_input_primary_disabled_text_color: 'var(--input-primary-disabled-text-color)',
  tag_input_primary_disabled_placeholder_text_color:
    'var(--input-primary-disabled-placeholder-text-color)',

  tag_input_success_background_color: 'var(--input-success-background-color)',
  tag_input_success_border_color: 'var(--input-success-border-color)',
  tag_input_success_text_color: 'var(--input-success-text-color)',
  tag_input_success_placeholder_text_color: 'var(--input-success-placeholder-text-color)',
  tag_input_success_focus_background_color: 'var(--input-success-focus-background-color)',
  tag_input_success_focus_border_color: 'var(--input-success-focus-border-color)',
  tag_input_success_disabled_text_color: 'var(--input-success-disabled-text-color)',
  tag_input_success_disabled_placeholder_text_color:
    'var(--input-success-disabled-placeholder-text-color)',

  tag_input_info_background_color: 'var(--input-info-background-color)',
  tag_input_info_border_color: 'var(--input-info-border-color)',
  tag_input_info_text_color: 'var(--input-info-text-color)',
  tag_input_info_placeholder_text_color: 'var(--input-info-placeholder-text-color)',
  tag_input_info_focus_background_color: 'var(--input-info-focus-background-color)',
  tag_input_info_focus_border_color: 'var(--input-info-focus-border-color)',
  tag_input_info_disabled_text_color: 'var(--input-info-disabled-text-color)',
  tag_input_info_disabled_placeholder_text_color:
    'var(--input-info-disabled-placeholder-text-color)',

  tag_input_warning_background_color: 'var(--input-warning-background-color)',
  tag_input_warning_border_color: 'var(--input-warning-border-color)',
  tag_input_warning_text_color: 'var(--input-warning-text-color)',
  tag_input_warning_placeholder_text_color: 'var(--input-warning-placeholder-text-color)',
  tag_input_warning_focus_background_color: 'var(--input-warning-focus-background-color)',
  tag_input_warning_focus_border_color: 'var(--input-warning-focus-border-color)',
  tag_input_warning_disabled_text_color: 'var(--input-warning-disabled-text-color)',
  tag_input_warning_disabled_placeholder_text_color:
    'var(--input-warning-disabled-placeholder-text-color)',

  tag_input_danger_background_color: 'var(--input-danger-background-color)',
  tag_input_danger_border_color: 'var(--input-danger-border-color)',
  tag_input_danger_text_color: 'var(--input-danger-text-color)',
  tag_input_danger_placeholder_text_color: 'var(--input-danger-placeholder-text-color)',
  tag_input_danger_focus_background_color: 'var(--input-danger-focus-background-color)',
  tag_input_danger_focus_border_color: 'var(--input-danger-focus-border-color)',
  tag_input_danger_disabled_text_color: 'var(--input-danger-disabled-text-color)',
  tag_input_danger_disabled_placeholder_text_color:
    'var(--input-danger-disabled-placeholder-text-color)',

  tag_input_control_background_color: 'var(--input-control-background-color)',
  tag_input_control_border_color: 'var(--input-control-border-color)',
  tag_input_control_text_color: 'var(--input-control-text-color)',
  tag_input_control_placeholder_text_color: 'var(--input-control-placeholder-text-color)',
  tag_input_control_focus_background_color: 'var(--input-control-focus-background-color)',
  tag_input_control_focus_border_color: 'var(--input-control-focus-border-color)',
  tag_input_control_disabled_text_color: 'var(--input-control-disabled-text-color)',
  tag_input_control_disabled_placeholder_text_color:
    'var(--input-control-disabled-placeholder-text-color)',

  tag_input_tiny_text_font_size: 'var(--input-tiny-text-font-size)',
  tag_input_tiny_text_font_weight: 'var(--input-tiny-text-font-weight)',
  tag_input_tiny_text_line_height: 'var(--input-tiny-text-line-height)',
  tag_input_tiny_placeholder_text_font_size: 'var(--input-tiny-placeholder-text-font-size)',
  tag_input_tiny_placeholder_text_font_weight: 'var(--input-tiny-placeholder-text-font-weight)',
  tag_input_tiny_placeholder_text_line_height: 'var(--input-tiny-placeholder-text-line-height)',
  tag_input_tiny_padding: '0.125rem 0',

  tag_input_small_text_font_size: 'var(--input-small-text-font-size)',
  tag_input_small_text_font_weight: 'var(--input-small-text-font-weight)',
  tag_input_small_text_line_height: 'var(--input-small-text-line-height)',
  tag_input_small_placeholder_text_font_size: 'var(--input-small-placeholder-text-font-size)',
  tag_input_small_placeholder_text_font_weight: 'var(--input-small-placeholder-text-font-weight)',
  tag_input_small_placeholder_text_line_height: 'var(--input-small-placeholder-text-line-height)',
  tag_input_small_padding: '0.125rem 0',

  tag_input_medium_text_font_size: 'var(--input-medium-text-font-size)',
  tag_input_medium_text_font_weight: 'var(--input-medium-text-font-weight)',
  tag_input_medium_text_line_height: 'var(--input-medium-text-line-height)',
  tag_input_medium_placeholder_text_font_size: 'var(--input-medium-placeholder-text-font-size)',
  tag_input_medium_placeholder_text_font_weight: 'var(--input-medium-placeholder-text-font-weight)',
  tag_input_medium_placeholder_text_line_height: 'var(--input-medium-placeholder-text-line-height)',
  tag_input_medium_padding: '0.25rem 0',

  tag_input_large_text_font_size: 'var(--input-large-text-font-size)',
  tag_input_large_text_font_weight: 'var(--input-large-text-font-weight)',
  tag_input_large_text_line_height: 'var(--input-large-text-line-height)',
  tag_input_large_placeholder_text_font_size: 'var(--input-large-placeholder-text-font-size)',
  tag_input_large_placeholder_text_font_weight: 'var(--input-large-placeholder-text-font-weight)',
  tag_input_large_placeholder_text_line_height: 'var(--input-large-placeholder-text-line-height)',
  tag_input_large_padding: '0.375rem 0',

  tag_input_giant_text_font_size: 'var(--input-giant-text-font-size)',
  tag_input_giant_text_font_weight: 'var(--input-giant-text-font-weight)',
  tag_input_giant_text_line_height: 'var(--input-giant-text-line-height)',
  tag_input_giant_placeholder_text_font_size: 'var(--input-giant-placeholder-text-font-size)',
  tag_input_giant_placeholder_text_font_weight: 'var(--input-giant-placeholder-text-font-weight)',
  tag_input_giant_placeholder_text_line_height: 'var(--input-giant-placeholder-text-line-height)',
  tag_input_giant_padding: '0.5rem 0'
};
