import { NebularThemeTooltip } from '../types/nebular-theme';

export const DefaultThemeTooltip: NebularThemeTooltip = {
  tooltip_background_color: 'var(--background-alternative-color-3)',
  tooltip_border_color: 'transparent',
  tooltip_border_style: 'dashed',
  tooltip_border_width: '0',
  tooltip_border_radius: 'var(--border-radius)',
  tooltip_padding: '0.5rem 1rem',
  tooltip_text_color: 'var(--text-alternate-color)',
  tooltip_text_font_family: 'var(--text-caption-font-family)',
  tooltip_text_font_size: 'var(--text-caption-font-size)',
  tooltip_text_font_weight: 'var(--text-caption-font-weight)',
  tooltip_text_line_height: 'var(--text-caption-line-height)',
  tooltip_icon_height: '1rem',
  tooltip_icon_width: '1rem',
  tooltip_max_width: '16rem',

  tooltip_basic_background_color: 'var(--background-basic-color-3)',
  tooltip_basic_border_color: 'transparent',
  tooltip_basic_text_color: 'var(--text-basic-color)',
  tooltip_primary_background_color: 'var(--color-primary-default)',
  tooltip_primary_border_color: 'transparent',
  tooltip_primary_text_color: 'var(--text-control-color)',
  tooltip_info_background_color: 'var(--color-info-default)',
  tooltip_info_border_color: 'transparent',
  tooltip_info_text_color: 'var(--text-control-color)',
  tooltip_success_background_color: 'var(--color-success-default)',
  tooltip_success_border_color: 'transparent',
  tooltip_success_text_color: 'var(--text-control-color)',
  tooltip_warning_background_color: 'var(--color-warning-default)',
  tooltip_warning_border_color: 'transparent',
  tooltip_warning_text_color: 'var(--text-control-color)',
  tooltip_danger_background_color: 'var(--color-danger-default)',
  tooltip_danger_border_color: 'transparent',
  tooltip_danger_text_color: 'var(--text-control-color)',
  tooltip_control_background_color: 'var(--color-control-default)',
  tooltip_control_border_color: 'transparent',
  tooltip_control_text_color: 'var(--color-basic-800)',
  tooltip_shadow: 'var(--shadow)'
};
