import { NebularThemeFormField } from '../types/nebular-theme';

export const DefaultThemeFormField: NebularThemeFormField = {
  form_field_tiny_max_width: 'var(--input-tiny-max-width)',
  form_field_small_max_width: 'var(--input-small-max-width)',
  form_field_medium_max_width: 'var(--input-medium-max-width)',
  form_field_large_max_width: 'var(--input-large-max-width)',
  form_field_giant_max_width: 'var(--input-giant-max-width)',

  form_field_addon_basic_text_color: 'var(--color-basic-600)',
  form_field_addon_basic_highlight_text_color: 'var(--color-primary-500)',
  form_field_addon_primary_text_color: 'var(--color-primary-500)',
  form_field_addon_primary_highlight_text_color: 'var(--color-primary-600)',
  form_field_addon_success_text_color: 'var(--color-success-500)',
  form_field_addon_success_highlight_text_color: 'var(--color-success-600)',
  form_field_addon_info_text_color: 'var(--color-info-500)',
  form_field_addon_info_highlight_text_color: 'var(--color-info-600)',
  form_field_addon_warning_text_color: 'var(--color-warning-500)',
  form_field_addon_warning_highlight_text_color: 'var(--color-warning-600)',
  form_field_addon_danger_text_color: 'var(--color-danger-500)',
  form_field_addon_danger_highlight_text_color: 'var(--color-danger-600)',
  form_field_addon_control_text_color: 'var(--color-control-default)',
  form_field_addon_control_highlight_text_color: 'var(--color-control-default)',
  form_field_addon_disabled_text_color: 'var(--text-disabled-color)',

  form_field_addon_tiny_height: '1.5rem',
  form_field_addon_tiny_width: 'var(--form-field-addon-tiny-height)',
  form_field_addon_tiny_icon_size: 'var(--button-tiny-icon-size)',
  form_field_addon_tiny_font_size: 'var(--text-button-tiny-font-size)',
  form_field_addon_tiny_line_height: 'var(--text-button-tiny-line-height)',
  form_field_addon_tiny_font_weight: 'var(--text-button-font-weight)',
  form_field_addon_small_height: '2rem',
  form_field_addon_small_width: 'var(--form-field-addon-small-height)',
  form_field_addon_small_icon_size: 'var(--button-small-icon-size)',
  form_field_addon_small_font_size: 'var(--text-button-small-font-size)',
  form_field_addon_small_line_height: 'var(--text-button-small-line-height)',
  form_field_addon_small_font_weight: 'var(--text-button-font-weight)',
  form_field_addon_medium_height: '2.5rem',
  form_field_addon_medium_width: 'var(--form-field-addon-medium-height)',
  form_field_addon_medium_icon_size: 'var(--button-medium-icon-size)',
  form_field_addon_medium_font_size: 'var(--text-button-medium-font-size)',
  form_field_addon_medium_line_height: 'var(--text-button-medium-line-height)',
  form_field_addon_medium_font_weight: 'var(--text-button-font-weight)',
  form_field_addon_large_height: '3rem',
  form_field_addon_large_width: 'var(--form-field-addon-large-height)',
  form_field_addon_large_icon_size: 'var(--button-large-icon-size)',
  form_field_addon_large_font_size: 'var(--text-button-large-font-size)',
  form_field_addon_large_line_height: 'var(--text-button-large-line-height)',
  form_field_addon_large_font_weight: 'var(--text-button-font-weight)',
  form_field_addon_giant_height: '3.5rem',
  form_field_addon_giant_width: 'var(--form-field-addon-giant-height)',
  form_field_addon_giant_icon_size: 'var(--button-giant-icon-size)',
  form_field_addon_giant_font_size: 'var(--text-button-giant-font-size)',
  form_field_addon_giant_line_height: 'var(--text-button-giant-line-height)',
  form_field_addon_giant_font_weight: 'var(--text-button-font-weight)'
};
