import { NebularThemeCore } from '../types';
import * as constants from './DefaultThemeConstants';

export const DefaultThemeCore: NebularThemeCore = {
  theme_name: 'default',
  isDarkTheme: false,
  color_primary_100: constants.color_primary_100,
  color_primary_200: constants.color_primary_200,
  color_primary_300: constants.color_primary_300,
  color_primary_400: constants.color_primary_400,
  color_primary_500: constants.color_primary_500,
  color_primary_600: constants.color_primary_600,
  color_primary_700: constants.color_primary_700,
  color_primary_800: constants.color_primary_800,
  color_primary_900: constants.color_primary_900,

  color_primary_transparent_100: constants.color_primary_transparent_100,
  color_primary_transparent_200: constants.color_primary_transparent_200,
  color_primary_transparent_300: constants.color_primary_transparent_300,
  color_primary_transparent_400: constants.color_primary_transparent_400,
  color_primary_transparent_500: constants.color_primary_transparent_500,
  color_primary_transparent_600: constants.color_primary_transparent_600,

  color_success_100: constants.color_success_100,
  color_success_200: constants.color_success_200,
  color_success_300: constants.color_success_300,
  color_success_400: constants.color_success_400,
  color_success_500: constants.color_success_500,
  color_success_600: constants.color_success_600,
  color_success_700: constants.color_success_700,
  color_success_800: constants.color_success_800,
  color_success_900: constants.color_success_900,

  color_success_transparent_100: constants.color_success_transparent_100,
  color_success_transparent_200: constants.color_success_transparent_200,
  color_success_transparent_300: constants.color_success_transparent_300,
  color_success_transparent_400: constants.color_success_transparent_400,
  color_success_transparent_500: constants.color_success_transparent_500,
  color_success_transparent_600: constants.color_success_transparent_600,

  color_info_100: constants.color_info_100,
  color_info_200: constants.color_info_200,
  color_info_300: constants.color_info_300,
  color_info_400: constants.color_info_400,
  color_info_500: constants.color_info_500,
  color_info_600: constants.color_info_600,
  color_info_700: constants.color_info_700,
  color_info_800: constants.color_info_800,
  color_info_900: constants.color_info_900,

  color_info_transparent_100: constants.color_info_transparent_100,
  color_info_transparent_200: constants.color_info_transparent_200,
  color_info_transparent_300: constants.color_info_transparent_300,
  color_info_transparent_400: constants.color_info_transparent_400,
  color_info_transparent_500: constants.color_info_transparent_500,
  color_info_transparent_600: constants.color_info_transparent_600,

  color_warning_100: constants.color_warning_100,
  color_warning_200: constants.color_warning_200,
  color_warning_300: constants.color_warning_300,
  color_warning_400: constants.color_warning_400,
  color_warning_500: constants.color_warning_500,
  color_warning_600: constants.color_warning_600,
  color_warning_700: constants.color_warning_700,
  color_warning_800: constants.color_warning_800,
  color_warning_900: constants.color_warning_900,

  color_warning_transparent_100: constants.color_warning_transparent_100,
  color_warning_transparent_200: constants.color_warning_transparent_200,
  color_warning_transparent_300: constants.color_warning_transparent_300,
  color_warning_transparent_400: constants.color_warning_transparent_400,
  color_warning_transparent_500: constants.color_warning_transparent_500,
  color_warning_transparent_600: constants.color_warning_transparent_600,

  color_danger_100: constants.color_danger_100,
  color_danger_200: constants.color_danger_200,
  color_danger_300: constants.color_danger_300,
  color_danger_400: constants.color_danger_400,
  color_danger_500: constants.color_danger_500,
  color_danger_600: constants.color_danger_600,
  color_danger_700: constants.color_danger_700,
  color_danger_800: constants.color_danger_800,
  color_danger_900: constants.color_danger_900,

  color_danger_transparent_100: constants.color_danger_transparent_100,
  color_danger_transparent_200: constants.color_danger_transparent_200,
  color_danger_transparent_300: constants.color_danger_transparent_300,
  color_danger_transparent_400: constants.color_danger_transparent_400,
  color_danger_transparent_500: constants.color_danger_transparent_500,
  color_danger_transparent_600: constants.color_danger_transparent_600,

  color_basic_100: constants.color_basic_100,
  color_basic_200: constants.color_basic_200,
  color_basic_300: constants.color_basic_300,
  color_basic_400: constants.color_basic_400,
  color_basic_500: constants.color_basic_500,
  color_basic_600: constants.color_basic_600,
  color_basic_700: constants.color_basic_700,
  color_basic_800: constants.color_basic_800,
  color_basic_900: constants.color_basic_900,
  color_basic_1000: constants.color_basic_1000,
  color_basic_1100: constants.color_basic_1100,

  color_basic_transparent_100: constants.color_basic_transparent_100,
  color_basic_transparent_200: constants.color_basic_transparent_200,
  color_basic_transparent_300: constants.color_basic_transparent_300,
  color_basic_transparent_400: constants.color_basic_transparent_400,
  color_basic_transparent_500: constants.color_basic_transparent_500,
  color_basic_transparent_600: constants.color_basic_transparent_600,

  color_basic_control_transparent_100: constants.color_basic_control_transparent_100,
  color_basic_control_transparent_200: constants.color_basic_control_transparent_200,
  color_basic_control_transparent_300: constants.color_basic_control_transparent_300,
  color_basic_control_transparent_400: constants.color_basic_control_transparent_400,
  color_basic_control_transparent_500: constants.color_basic_control_transparent_500,
  color_basic_control_transparent_600: constants.color_basic_control_transparent_600,

  color_basic_focus: constants.color_basic_focus,
  color_basic_hover: constants.color_basic_hover,
  color_basic_default: constants.color_basic_default,
  color_basic_active: constants.color_basic_active,
  color_basic_disabled: constants.color_basic_disabled,
  color_basic_focus_border: constants.color_basic_focus_border,
  color_basic_hover_border: constants.color_basic_hover_border,
  color_basic_default_border: constants.color_basic_default_border,
  color_basic_active_border: constants.color_basic_active_border,
  color_basic_disabled_border: constants.color_basic_disabled_border,

  color_basic_transparent_focus: constants.color_basic_transparent_focus,
  color_basic_transparent_hover: constants.color_basic_transparent_hover,
  color_basic_transparent_default: constants.color_basic_transparent_default,
  color_basic_transparent_active: constants.color_basic_transparent_active,
  color_basic_transparent_disabled: constants.color_basic_transparent_disabled,
  color_basic_transparent_focus_border: constants.color_basic_transparent_focus_border,
  color_basic_transparent_hover_border: constants.color_basic_transparent_hover_border,
  color_basic_transparent_default_border: constants.color_basic_transparent_default_border,
  color_basic_transparent_active_border: constants.color_basic_transparent_active_border,
  color_basic_transparent_disabled_border: constants.color_basic_transparent_disabled_border,

  color_primary_focus: constants.color_primary_focus,
  color_primary_hover: constants.color_primary_hover,
  color_primary_default: constants.color_primary_default,
  color_primary_active: constants.color_primary_active,
  color_primary_disabled: constants.color_primary_disabled,
  color_primary_focus_border: constants.color_primary_focus_border,
  color_primary_hover_border: constants.color_primary_hover_border,
  color_primary_default_border: constants.color_primary_default_border,
  color_primary_active_border: constants.color_primary_active_border,
  color_primary_disabled_border: constants.color_primary_disabled_border,

  color_primary_transparent_focus: constants.color_primary_transparent_focus,
  color_primary_transparent_hover: constants.color_primary_transparent_hover,
  color_primary_transparent_default: constants.color_primary_transparent_default,
  color_primary_transparent_active: constants.color_primary_transparent_active,
  color_primary_transparent_disabled: constants.color_primary_transparent_disabled,
  color_primary_transparent_focus_border: constants.color_primary_transparent_focus_border,
  color_primary_transparent_hover_border: constants.color_primary_transparent_hover_border,
  color_primary_transparent_default_border: constants.color_primary_transparent_default_border,
  color_primary_transparent_active_border: constants.color_primary_transparent_active_border,
  color_primary_transparent_disabled_border: constants.color_primary_transparent_disabled_border,

  color_success_focus: constants.color_success_focus,
  color_success_hover: constants.color_success_hover,
  color_success_default: constants.color_success_default,
  color_success_active: constants.color_success_active,
  color_success_disabled: constants.color_success_disabled,
  color_success_focus_border: constants.color_success_focus_border,
  color_success_hover_border: constants.color_success_hover_border,
  color_success_default_border: constants.color_success_default_border,
  color_success_active_border: constants.color_success_active_border,
  color_success_disabled_border: constants.color_success_disabled_border,

  color_success_transparent_focus: constants.color_success_transparent_focus,
  color_success_transparent_focus_border: constants.color_success_transparent_focus_border,
  color_success_transparent_hover: constants.color_success_transparent_hover,
  color_success_transparent_hover_border: constants.color_success_transparent_hover_border,
  color_success_transparent_default: constants.color_success_transparent_default,
  color_success_transparent_default_border: constants.color_success_transparent_default_border,
  color_success_transparent_active: constants.color_success_transparent_active,
  color_success_transparent_active_border: constants.color_success_transparent_active_border,
  color_success_transparent_disabled: constants.color_success_transparent_disabled,
  color_success_transparent_disabled_border: constants.color_success_transparent_disabled_border,

  color_info_focus: constants.color_info_focus,
  color_info_hover: constants.color_info_hover,
  color_info_default: constants.color_info_default,
  color_info_active: constants.color_info_active,
  color_info_disabled: constants.color_info_disabled,
  color_info_focus_border: constants.color_info_focus_border,
  color_info_hover_border: constants.color_info_hover_border,
  color_info_default_border: constants.color_info_default_border,
  color_info_active_border: constants.color_info_active_border,
  color_info_disabled_border: constants.color_info_disabled_border,

  color_info_transparent_focus: constants.color_info_transparent_focus,
  color_info_transparent_hover: constants.color_info_transparent_hover,
  color_info_transparent_default: constants.color_info_transparent_default,
  color_info_transparent_active: constants.color_info_transparent_active,
  color_info_transparent_disabled: constants.color_info_transparent_disabled,
  color_info_transparent_focus_border: constants.color_info_transparent_focus_border,
  color_info_transparent_hover_border: constants.color_info_transparent_hover_border,
  color_info_transparent_default_border: constants.color_info_transparent_default_border,
  color_info_transparent_active_border: constants.color_info_transparent_active_border,
  color_info_transparent_disabled_border: constants.color_info_transparent_disabled_border,

  color_warning_focus: constants.color_warning_focus,
  color_warning_hover: constants.color_warning_hover,
  color_warning_default: constants.color_warning_default,
  color_warning_active: constants.color_warning_active,
  color_warning_disabled: constants.color_warning_disabled,
  color_warning_focus_border: constants.color_warning_focus_border,
  color_warning_hover_border: constants.color_warning_hover_border,
  color_warning_default_border: constants.color_warning_default_border,
  color_warning_active_border: constants.color_warning_active_border,
  color_warning_disabled_border: constants.color_warning_disabled_border,

  color_warning_transparent_focus: constants.color_warning_transparent_focus,
  color_warning_transparent_hover: constants.color_warning_transparent_hover,
  color_warning_transparent_default: constants.color_warning_transparent_default,
  color_warning_transparent_active: constants.color_warning_transparent_active,
  color_warning_transparent_disabled: constants.color_warning_transparent_disabled,
  color_warning_transparent_focus_border: constants.color_warning_transparent_focus_border,
  color_warning_transparent_hover_border: constants.color_warning_transparent_hover_border,
  color_warning_transparent_default_border: constants.color_warning_transparent_default_border,
  color_warning_transparent_active_border: constants.color_warning_transparent_active_border,
  color_warning_transparent_disabled_border: constants.color_warning_transparent_disabled_border,

  color_danger_focus: constants.color_danger_focus,
  color_danger_hover: constants.color_danger_hover,
  color_danger_default: constants.color_danger_default,
  color_danger_active: constants.color_danger_active,
  color_danger_disabled: constants.color_danger_disabled,
  color_danger_focus_border: constants.color_danger_focus_border,
  color_danger_hover_border: constants.color_danger_hover_border,
  color_danger_default_border: constants.color_danger_default_border,
  color_danger_active_border: constants.color_danger_active_border,
  color_danger_disabled_border: constants.color_danger_disabled_border,

  color_danger_transparent_focus: constants.color_danger_transparent_focus,
  color_danger_transparent_hover: constants.color_danger_transparent_hover,
  color_danger_transparent_default: constants.color_danger_transparent_default,
  color_danger_transparent_active: constants.color_danger_transparent_active,
  color_danger_transparent_disabled: constants.color_danger_transparent_disabled,
  color_danger_transparent_focus_border: constants.color_danger_transparent_focus_border,
  color_danger_transparent_hover_border: constants.color_danger_transparent_hover_border,
  color_danger_transparent_default_border: constants.color_danger_transparent_default_border,
  color_danger_transparent_active_border: constants.color_danger_transparent_active_border,
  color_danger_transparent_disabled_border: constants.color_danger_transparent_disabled_border,

  color_control_focus: constants.color_control_focus,
  color_control_hover: constants.color_control_hover,
  color_control_default: constants.color_control_default,
  color_control_active: constants.color_control_active,
  color_control_disabled: constants.color_control_disabled,
  color_control_focus_border: constants.color_control_focus_border,
  color_control_hover_border: constants.color_control_hover_border,
  color_control_default_border: constants.color_control_default_border,
  color_control_active_border: constants.color_control_active_border,
  color_control_disabled_border: constants.color_control_disabled_border,

  color_control_transparent_focus: constants.color_control_transparent_focus,
  color_control_transparent_hover: constants.color_control_transparent_hover,
  color_control_transparent_default: constants.color_control_transparent_default,
  color_control_transparent_active: constants.color_control_transparent_active,
  color_control_transparent_disabled: constants.color_control_transparent_disabled,
  color_control_transparent_focus_border: constants.color_control_transparent_focus_border,
  color_control_transparent_hover_border: constants.color_control_transparent_hover_border,
  color_control_transparent_default_border: constants.color_control_transparent_default_border,
  color_control_transparent_active_border: constants.color_control_transparent_active_border,
  color_control_transparent_disabled_border: constants.color_control_transparent_disabled_border,

  background_basic_color_1: constants.background_basic_color_1,
  background_basic_color_2: constants.background_basic_color_2,
  background_basic_color_3: constants.background_basic_color_3,
  background_basic_color_4: constants.background_basic_color_4,

  border_basic_color_1: constants.border_basic_color_1,
  border_basic_color_2: constants.border_basic_color_2,
  border_basic_color_3: constants.border_basic_color_3,
  border_basic_color_4: constants.border_basic_color_4,
  border_basic_color_5: constants.border_basic_color_5,

  background_alternative_color_1: constants.background_alternative_color_1,
  background_alternative_color_2: constants.background_alternative_color_2,
  background_alternative_color_3: constants.background_alternative_color_3,
  background_alternative_color_4: constants.background_alternative_color_4,

  border_alternative_color_1: constants.border_alternative_color_1,
  border_alternative_color_2: constants.border_alternative_color_2,
  border_alternative_color_3: constants.border_alternative_color_3,
  border_alternative_color_4: constants.border_alternative_color_4,
  border_alternative_color_5: constants.border_alternative_color_5,

  background_primary_color_1: constants.background_primary_color_1,
  background_primary_color_2: constants.background_primary_color_2,
  background_primary_color_3: constants.background_primary_color_3,
  background_primary_color_4: constants.background_primary_color_4,

  border_primary_color_1: constants.border_primary_color_1,
  border_primary_color_2: constants.border_primary_color_2,
  border_primary_color_3: constants.border_primary_color_3,
  border_primary_color_4: constants.border_primary_color_4,
  border_primary_color_5: constants.border_primary_color_5,

  text_basic_color: constants.text_basic_color,
  text_alternate_color: constants.text_alternate_color,
  text_control_color: constants.text_control_color,
  text_disabled_color: constants.text_disabled_color,
  text_hint_color: constants.text_hint_color,

  text_primary_color: constants.text_primary_color,
  text_primary_focus_color: constants.text_primary_focus_color,
  text_primary_hover_color: constants.text_primary_hover_color,
  text_primary_active_color: constants.text_primary_active_color,
  text_primary_disabled_color: constants.text_primary_disabled_color,

  text_success_color: constants.text_success_color,
  text_success_focus_color: constants.text_success_focus_color,
  text_success_hover_color: constants.text_success_hover_color,
  text_success_active_color: constants.text_success_active_color,
  text_success_disabled_color: constants.text_success_disabled_color,

  text_info_color: constants.text_info_color,
  text_info_focus_color: constants.text_info_focus_color,
  text_info_hover_color: constants.text_info_hover_color,
  text_info_active_color: constants.text_info_active_color,
  text_info_disabled_color: constants.text_info_disabled_color,

  text_warning_color: constants.text_warning_color,
  text_warning_focus_color: constants.text_warning_focus_color,
  text_warning_hover_color: constants.text_warning_hover_color,
  text_warning_active_color: constants.text_warning_active_color,
  text_warning_disabled_color: constants.text_warning_disabled_color,

  text_danger_color: constants.text_danger_color,
  text_danger_focus_color: constants.text_danger_focus_color,
  text_danger_hover_color: constants.text_danger_hover_color,
  text_danger_active_color: constants.text_danger_active_color,
  text_danger_disabled_color: constants.text_danger_disabled_color,

  font_family_primary: constants.font_family_primary,
  font_family_secondary: constants.font_family_secondary,

  text_heading_1_font_family: constants.text_heading_1_font_family,
  text_heading_1_font_size: constants.text_heading_1_font_size,
  text_heading_1_font_weight: constants.text_heading_1_font_weight,
  text_heading_1_line_height: constants.text_heading_1_line_height,

  text_heading_2_font_family: constants.text_heading_2_font_family,
  text_heading_2_font_size: constants.text_heading_2_font_size,
  text_heading_2_font_weight: constants.text_heading_2_font_weight,
  text_heading_2_line_height: constants.text_heading_2_line_height,

  text_heading_3_font_family: constants.text_heading_3_font_family,
  text_heading_3_font_size: constants.text_heading_3_font_size,
  text_heading_3_font_weight: constants.text_heading_3_font_weight,
  text_heading_3_line_height: constants.text_heading_3_line_height,

  text_heading_4_font_family: constants.text_heading_4_font_family,
  text_heading_4_font_size: constants.text_heading_4_font_size,
  text_heading_4_font_weight: constants.text_heading_4_font_weight,
  text_heading_4_line_height: constants.text_heading_4_line_height,

  text_heading_5_font_family: constants.text_heading_5_font_family,
  text_heading_5_font_size: constants.text_heading_5_font_size,
  text_heading_5_font_weight: constants.text_heading_5_font_weight,
  text_heading_5_line_height: constants.text_heading_5_line_height,

  text_heading_6_font_family: constants.text_heading_6_font_family,
  text_heading_6_font_size: constants.text_heading_6_font_size,
  text_heading_6_font_weight: constants.text_heading_6_font_weight,
  text_heading_6_line_height: constants.text_heading_6_line_height,

  text_subtitle_font_family: constants.text_subtitle_font_family,
  text_subtitle_font_size: constants.text_subtitle_font_size,
  text_subtitle_font_weight: constants.text_subtitle_font_weight,
  text_subtitle_line_height: constants.text_subtitle_line_height,

  text_subtitle_2_font_family: constants.text_subtitle_2_font_family,
  text_subtitle_2_font_size: constants.text_subtitle_2_font_size,
  text_subtitle_2_font_weight: constants.text_subtitle_2_font_weight,
  text_subtitle_2_line_height: constants.text_subtitle_2_line_height,

  text_paragraph_font_family: constants.text_paragraph_font_family,
  text_paragraph_font_size: constants.text_paragraph_font_size,
  text_paragraph_font_weight: constants.text_paragraph_font_weight,
  text_paragraph_line_height: constants.text_paragraph_line_height,

  text_paragraph_2_font_family: constants.text_paragraph_2_font_family,
  text_paragraph_2_font_size: constants.text_paragraph_2_font_size,
  text_paragraph_2_font_weight: constants.text_paragraph_2_font_weight,
  text_paragraph_2_line_height: constants.text_paragraph_2_line_height,

  text_label_font_family: constants.text_label_font_family,
  text_label_font_size: constants.text_label_font_size,
  text_label_font_weight: constants.text_label_font_weight,
  text_label_line_height: constants.text_label_line_height,

  text_caption_font_family: constants.text_caption_font_family,
  text_caption_font_size: constants.text_caption_font_size,
  text_caption_font_weight: constants.text_caption_font_weight,
  text_caption_line_height: constants.text_caption_line_height,

  text_caption_2_font_family: constants.text_caption_2_font_family,
  text_caption_2_font_size: constants.text_caption_2_font_size,
  text_caption_2_font_weight: constants.text_caption_2_font_weight,
  text_caption_2_line_height: constants.text_caption_2_line_height,

  text_button_font_family: constants.text_button_font_family,
  text_button_font_weight: constants.text_button_font_weight,
  text_button_tiny_font_size: constants.text_button_tiny_font_size,
  text_button_tiny_line_height: constants.text_button_tiny_line_height,
  text_button_small_font_size: constants.text_button_small_font_size,
  text_button_small_line_height: constants.text_button_small_line_height,
  text_button_medium_font_size: constants.text_button_medium_font_size,
  text_button_medium_line_height: constants.text_button_medium_line_height,
  text_button_large_font_size: constants.text_button_large_font_size,
  text_button_large_line_height: constants.text_button_large_line_height,
  text_button_giant_font_size: constants.text_button_giant_font_size,
  text_button_giant_line_height: constants.text_button_giant_line_height,

  border_radius: constants.border_radius,

  outline_width: constants.outline_width,
  outline_color: constants.outline_color,

  scrollbar_color: constants.scrollbar_color,
  scrollbar_background_color: constants.scrollbar_background_color,
  scrollbar_width: constants.scrollbar_width,

  shadow: constants.shadow,

  divider_color: constants.divider_color,
  divider_style: constants.divider_style,
  divider_width: constants.divider_width,

  link_text_color: constants.link_text_color,
  link_text_decoration: constants.link_text_decoration,
  link_text_focus_color: constants.link_text_focus_color,
  link_text_hover_color: constants.link_text_hover_color,

  overlay_backdrop_background_color: 'rgba(0, 0, 0, 0.35)'
};
